### ISSUE TITLE
Team data not parsing

### ISSUE THREAD

**Issue by 0ArturkA** [gigobyte/HLTV#10]
Sometimes the name or id of one of the teams is not parsed.
`{
"id":2313372,
"team1":{
"name":"Majestic Lions",
"id":6576
},
"team2":{
"name":"",
"id":5412
},
"event":{
"name":"PG WAY Trnava 2017",
"id":null
},
"format":"Best of 3",
"maps":[
"ovp",
"inf",
"mrg"
],
"stars":0,
"live":true
}`

**Comment by 0ArturkA** [comment]
You can fix this? Because of this, the module does not work.

**Comment by gigobyte** [comment]
Which methods does this bug affect?

**Comment by 0ArturkA** [comment]
I meant that this function is very important where I use it and without it nothing works.

**Comment by gigobyte** [comment]
You never mentioned which function. From the looks of it, it's the getMatches function, is that correct?

**Comment by 0ArturkA** [comment]
Yes, getMatches function.

**Comment by 0ArturkA** [comment]
Can you fix?

**Comment by gigobyte** [comment]
Issue should be fixed in v2.1.1

**Comment by 0ArturkA** [comment]
First live match: `{
"id":2313358,
"team1":{
"name":"Goliath",
"id":8193
},
"team2":{
"name":"",
"id":5153
},
"event":{
"name":"ESEA Open Season 25 South Africa",
"id":3043
},
"format":"Best of 3",
"maps":[
"ovp",
"cch",
"nuke"
],
"stars":0,
"live":true
}`

**Comment by gigobyte** [comment]
I can't reproduce it, this bug is fixed in the latest version, have you updated?

`{ id: 2313358,
    team1: { name: 'Goliath', id: 8193 },
    team2: { name: 'eNergy', id: 5153 },
    event: { name: 'ESEA Open Season 25 South Africa', id: 3043 },
    format: 'Best of 3',
    maps: [ 'ovp', 'cch', 'nuke' ],
    stars: 0,
    live: true }`

**Comment by 0ArturkA** [comment]
Yes, i update.
