### ISSUE TITLE
getPlayer not working

### ISSUE THREAD

**Issue by alny** [gigobyte/HLTV#100]
Returns TypeError: Cannot read property 'split' of undefined

**Comment by clappis** [comment]
Do you can pass more details? like the player id?

**Comment by alny** [comment]
Tried with 10+ players, still returns the same error

**Comment by gigobyte** [comment]
Seems like HLTV have updated their achievements tab in the player profile ([example link](https://www.hltv.org/player/483/Edward#tab-achievementBox)).

**Comment by gigobyte** [comment]
Luckily it was a simple fix, so I've published a new update that fixes the issue (v2.9.2).

**Comment by alny** [comment]
Cool thanks, works like a charm

**Comment by Carchuli** [comment]
Same problem here using last version of the package

id 7398 is dupreeh

` var idPlayer = 7398;

        HLTV.getPlayer({ id: idPlayer })
            .then((res) => {
                console.log(res)
            })
            .catch((err)=>{
                console.log(err);
            })`

> TypeError: Cannot read property 'split' of undefined

**Comment by gigobyte** [comment]
Can anyone look into this? The error should show the line number and the code is extremely simple, it's basically jQuery.

**Comment by Carchuli** [comment]
> Can anyone look into this? The error should show the line number and the code is extremely simple, it's basically jQuery.
> 
> Here is the [source](https://github.com/gigobyte/HLTV/blob/master/src/endpoints/getPlayer.ts) for `getPlayer`.

thanks for the quick reply, ill check the source code in order to try to find the error:

the error is in the following lines:

TypeError: Cannot read property 'split' of undefined
    at Object.exports.popSlashSource (C:\Users\---\node_modules\hltv\lib\utils\parsing.js:6:63)
    at Object.<anonymous> (C:\Users\----\node_modules\hltv\lib\endpoints\getPlayer.js:59:33)
    at step (C:\Users\---\node_modules\hltv\lib\endpoints\getPlayer.js:32:23)
    at Object.next (C:\Users\c---\node_modules\hltv\lib\endpoints\getPlayer.js:13:53)
    at fulfilled (C:\Users\---\node_modules\hltv\lib\endpoints\getPlayer.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by gigobyte** [comment]
The line that crashes is [line 21](https://github.com/gigobyte/HLTV/blob/master/src/endpoints/getPlayer.ts#L21), which means hltv changed the element for the country flag.

**Comment by gigobyte** [comment]
Fixed in `v2.12.2`
