### ISSUE TITLE
Match don't have additionalInfo

### ISSUE THREAD

**Issue by 0ArturkA** [gigobyte/HLTV#11]
This match does not have any additionalInfo - https://www.hltv.org/matches/2312432/infused-vs-excel-gfinity-elite-series

But modul try get additionalInfo and we get errors: 
`(node:11272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11272) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'split' of undefined`

**Comment by gigobyte** [comment]
I can't reproduce this. When I run`HLTV.getMatch({id: 2312432})` everything runs fine and additionalInfo is an empty string

**Comment by 0ArturkA** [comment]
Means I just did not handle it
