### ISSUE TITLE
Scorebot is not working

### ISSUE THREAD

**Issue by Tonychen0227** [gigobyte/HLTV#110]
So far, I have had 3 instances where a scorebot fails to connect despite it existing on the actual website. Please let me know how I can help fix that!

**Comment by gigobyte** [comment]
By now working do you mean that there are no updates or that an exception is thrown?

**Comment by gigobyte** [comment]
Thanks for reporting. It is very possible that they changed how the scorebot works, it's not the first time they've done it.

If you are willing to help you can reverse engineer how HLTV connects to the websocket - search for any code that looks up `data-scorebot-id` and go from there. You can also look at how [this library connects currently](https://github.com/gigobyte/HLTV/blob/master/src/endpoints/connectToScorebot.ts#L15) if you need some hints.

**Comment by Tonychen0227** [comment]
Right now (very quickly as I am at work), I see a call to https://scorebot-secure.hltv.org/scorebotClientApi.js?v9=??? using Chrome Dev Tools (I tried https://scorebot-secure.hltv.org/scorebotClientApi.js?v9=2330143) which returns seemingly incomprehensible code (I am not sure what it actually means since I'm not familiar with JavaScript). Let me know if that's what you're looking for.

**Comment by Tonychen0227** [comment]
Also this line of code in the HTML:

              <div id="scoreboardElement" data-scorebot-url="https://cf1-scorebot.hltv.org,https://cf2-scorebot.hltv.org" data-scorebot-id="2330143"></div>

**Comment by gigobyte** [comment]
Well yes, I know that about that HTML element and script, otherwise how would I tell you to look for `data-scorebot-id` :grin

**Comment by gigobyte** [comment]
Fixed in the newest version
