### ISSUE TITLE
Live FullMatch teams names

### ISSUE THREAD

**Issue by 0ArturkA** [gigobyte/HLTV#12]
To get teams names you use - `$('div.teamName')`
But on this page with LIVE match 4 div with class teamName:
`
0:div.teamName
1:div.teamName
2:div.nameCell.teamName
3:div.nameCell.teamName
`
Last 2 on scorboard.

To get 1 team name you use: `$('div.teamName').first()` and this work
But for 2 team name you use `$('div.teamName').last()` and we get `3:div.nameCell.teamName` not `1:div.teamName`

Maybe worth using: `$('div.teamName').eq(0)` and `$('div.teamName').eq(1)`

**Comment by gigobyte** [comment]
The 2 `div.nameCell.teamName` appear only at runtime because the scoreboard is not in the source code but inserted with JS.
