### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by danidfm** [gigobyte/HLTV#121]
Hi,

I really love this API! 

However, I am trying to get information from the matches, and get the following error on the function **getMatchStats** (I think other methods have the same issue):

`TypeError: Cannot read property 'split' of undefined
`

Probably HLTV has changed the design of the urls.

Thanks!

**Comment by gigobyte** [comment]
Thanks for reporting, HLTV changes their pages quite often and this project relies on people catching that as I don't have enough time to check if everything runs or setup a CI process that does it.

Can you please paste some IDs you've tried?

**Comment by danidfm** [comment]
`HLTV.getMatchStats({id: 81284}).then((res) => {
    console.log(res);
  });`

That's what I've tried, so... https://www.hltv.org/stats/matches/mapstatsid/81284/alternate-attax-vs-vexed

I have been taken a look at the source code of the library, it fails here: `node_modules/hltv/lib/endpoints/getMatchStats.js:76:77`

I am not familiar with Node JS yet, we're staring a new project setting a simple Node JS server helped with Express and we barely understand how your code reaches to the elements in the page so we can't help to much :(

**Comment by gigobyte** [comment]
Your link is actually parsed by `getMatchMapStats`.

It seems like `getMatchStats` crashes because HLTV is crashing and returning an internal server error 500. So until they fix their issue this method won't work.

**Comment by danidfm** [comment]
Oh! My bad... it worked perfectly! 

And we have checked some others API end points and they retrieve all we need - that's awesome!

I'll close this ticket asap.

Thanks for the great work - keep it up!
