### ISSUE TITLE
getTeam x6tence galaxy only return 1 player

### ISSUE THREAD

**Issue by Carchuli** [gigobyte/HLTV#126]
I have found and issue and is that when calling the getTeam for x6tence galaxy(team id 9481) only returns one player

`HLTV.getTeam({ id: 9481 })
    .then((res=>{
        console.log(res)
    }))
`

and the result is:

`
{ name: 'x6tence Galaxy',
  logo: 'https://static.hltv.org/images/team/logo/9481',
  coverImage: undefined,
  location: 'Sweden',
  facebook: undefined,
  twitter: undefined,
  rank: 30,
  players: [ { name: 'freddieb', id: 9257 } ],
  recentResults:
   [ { matchID: undefined,
       enemyTeam: [Object],
.
.
.
.
.
.
. }`

As you can see it only return  one player, but in the hltv web it shows the 5 players: https://www.hltv.org/team/9481/x6tence-galaxy

**Comment by Carchuli** [comment]
I have found that in the x6 galaxy page, the name of some elements have been changed:

Example of an Astralis player:
`

<a href="/player/4954/Xyp9x" title="Xyp9x">
--
  | <div class="**overlayImageFrame**"><img src="https://static.hltv.org//images/playerprofile/bodyshot/compressed/4954.png" **class="bodyshot-team-img**" alt="Image of CS:GO player Xyp9x">
  | <div class="playerFlagName"><span class="gtSmartphone-only"><img alt="Denmark" src="https://static.hltv.org/images/bigflags/30x20/DK.gif" class="flag" title="Denmark"> </span><span class="text-ellipsis bold">Xyp9x</span></div>

`
x6 galaxy player:
`

<a href="/player/44/BARBARR" title="BARBARR">
--
  | <div class="**overlayImageFrame-square**"><img alt="André 'BARBARR' Möller" src="https://static.hltv.org/images/playerprofile/thumb/44/400.jpeg?v=5" **class="profileImage block**" title="André 'BARBARR' Möller">
  | <div class="playerFlagName"><span class="gtSmartphone-only"><img alt="Sweden" src="https://static.hltv.org/images/bigflags/30x20/SE.gif" class="flag" title="Sweden"> </span><span class="text-ellipsis bold">BARBARR</span></div>
  | </div>

`

**Comment by gigobyte** [comment]
Yes, HLTV has 2 layouts - one for top teams with fancy pictures and one for everyone else.
In getTeam we use [arePlayerPicturesOfficial](https://github.com/gigobyte/HLTV/blob/master/src/endpoints/getTeam.ts#L37) to distinguish the two.

Can you please try to make a PR with a fix? I would greatly appreciate it.

**Comment by gigobyte** [comment]
This was the first time I've seen a mix of official player pictures and default ones, it's fixed in the newest version.
