### ISSUE TITLE
Timezone of fetched matches

### ISSUE THREAD

**Issue by webbzac** [gigobyte/HLTV#129]
Hey,

Just a quick question - what timezone does `getMatchesStats` use for `startDate` and `endDate`? When I go on HLTV all matches are in my own timezone (GMT+12), but when I do a search for today's date it seems to be using a different timezone.

Many thanks

**Comment by gigobyte** [comment]
All dates returned are a [unix timestamps](https://en.wikipedia.org/wiki/Unix_time).
