### ISSUE TITLE
getMatchStats fails to execute

### ISSUE THREAD

**Issue by Kaszanas** [gigobyte/HLTV#145]
I have this code created:

    constructor(_id, arg) {
        this._id = _id;
        this.arg = arg;

        this.GetMatchStats(_id, arg);

    }

    GetMatchStats(_id, filename) {
        console.log("Getting MatchStats")
        HLTV.getMatchStats({ id: _id }).then(res => {
            saveFModule(res, filename)
        });
    }

Which would theoretically allow me to get the data from getMatchStats function.
Although I have found following errors to appear every time I am trying to make it work.

`(node:15556) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
warning.js:18
    at Object.<anonymous> (*\node_modules\hltv\lib\endpoints\getMatchStats.js:89:25)
    at step (*\node_modules\hltv\lib\endpoints\getMatchStats.js:43:23)
    at Object.next (*\node_modules\hltv\lib\endpoints\getMatchStats.js:24:53)
    at fulfilled (*\node_modules\hltv\lib\endpoints\getMatchStats.js:15:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
warning.js:18
(node:15556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I will be trying to fix it on my own. But in case I am not going to make it I am leaving it here ;)

**Comment by gigobyte** [comment]
What id did you use? You issue says that `getMatches` fails but your error stack shows `getMatchStats`.

**Comment by Kaszanas** [comment]
I entered the numeric representation of the ID shown below so basically "82830".
I used it in different match but it doesn't matter I guess ;) 

![image](https://user-images.githubusercontent.com/34846245/54528569-a802b480-497d-11e9-954e-38b73c444ca0.png)

**Comment by gigobyte** [comment]
The endpoint you're looking for is `getMatchMapStats`, which is for a single map.
