### ISSUE TITLE
Match score

### ISSUE THREAD

**Issue by 0ArturkA** [gigobyte/HLTV#15]
How i cant get match score when match end?

**Comment by gigobyte** [comment]
Can you please specify more what feature you want?

**Comment by 0ArturkA** [comment]
You don't parse end matches?

**Comment by 0ArturkA** [comment]
I need, when i use getMatch get match score if he end

**Comment by gigobyte** [comment]
The results are in the `result` property in the maps array. They're not in the friendliest format (e.g. `'13:16 (6:9; 7:7)'` but parsing that kind of strings is not very complicated.
