### ISSUE TITLE
Vertigo in map pool and not showed by API

### ISSUE THREAD

**Issue by LaCTuK** [gigobyte/HLTV#151]
So vertigo added to map pool and teams already using it in official matches
https://www.hltv.org/matches/2332185/ago-vs-nordavind-lootbet-season-2
Looks like API can't show it now.
Need to add vertigo to Map and MapSlug (maybe somewhere else?)

**Comment by gigobyte** [comment]
Fixed in https://github.com/gigobyte/HLTV/releases/tag/v2.14.1
