### ISSUE TITLE
Match betting odds

### ISSUE THREAD

**Issue by emha** [gigobyte/HLTV#159]
Hi,

is it possible to get the betting odds for a match similar to the website? Is it possible to integrate it? Don't need every odd displayed on the website just one for comparison.

Thanks in advance!

**Comment by gigobyte** [comment]
Hello, it's possible to parse the odds displayed in the match page, is that what you're looking for?

![image](https://user-images.githubusercontent.com/8791446/56467844-da944700-642c-11e9-8ad8-f5b262739c7a.png)

**Comment by emha** [comment]
Yeah that is exactly what I mean! Which endpoint do I have to use? I couldn't find the information.

Thank you very much!

**Comment by gigobyte** [comment]
It's not available currently, but if you want to contribute it's really easy to add this information to the current `getMatch` endpoint. Ping me if you need any help

**Comment by emha** [comment]
Perfect, will do that! Thank you very much!
