### ISSUE TITLE
Wrong month on getMatch

### ISSUE THREAD

**Issue by Sonic1305** [gigobyte/HLTV#178]
I tried to ge tthe date of the next match for the ESL One Cologne and noticed it says 3.6.2019 but it should be 3.7.2019.

**Comment by emha** [comment]
I tried it with the matchID `2334604`. The returned date `1562148000000` is correct. Which match did you use? Also please show your code so we can make sure there are no errors.

**Comment by gigobyte** [comment]
The date of the match is returned in [POSIX format](https://en.wikipedia.org/wiki/Unix_time). Can you confirm that you're converting it correctly to a date string?
