### ISSUE TITLE
Get mapstatsid with match id

### ISSUE THREAD

**Issue by tbshssnr** [gigobyte/HLTV#184]
Is it possible to get all matchstatsids from a match with the match id(e.g. 2334995) ?

**Comment by tbshssnr** [comment]
Maybe its a possibility to add an option to getMatchMapStats to filter with matchPageID?

**Comment by emha** [comment]
@tbshssnr  Do you mean to get the ID's for the single maps?
<img width="271" alt="Screenshot 2019-08-02 at 11 04 44" src="https://user-images.githubusercontent.com/1200347/62358653-63834a00-b515-11e9-8d51-8dfbd3a5325f.png">

**Comment by gigobyte** [comment]
Added `statsId` property in v2.16.3, also you can get all of the map stats ids from `match.maps.map(x => x.statsId)`
