### ISSUE TITLE
getPlayerStats

### ISSUE THREAD

**Issue by Joker21a** [gigobyte/HLTV#192]
HLTV.getPlayerStats({id: 7998,startDate: '2019-08-20', endDate: '2019=08-22'}).then(res => {
    console.log(res);
});

TypeError: Cannot read property 'split' of undefined

Error is on FILE: getPlayerStats.js on line 72
if (getInfo(3).text() !== 'No team') {
                        team = {
                            name: getInfo(3).text(),
                            id: Number(getInfo(3)
                                .attr('href')
                                .split('/')[3])
                        };
                    }

getInfo(3).text() is an empty string

Solution: in if add && getInfo(3).text() !== ''

**Comment by trevorblades** [comment]
Fixed by #195
