### ISSUE TITLE
"stopwatch" outcome on MatchMapStats

### ISSUE THREAD

**Issue by brenosabino** [gigobyte/HLTV#197]
Hi, I'm using your api for the first time. I tried to get stats for a specific map in a match and noticed a few rounds didnt show up in the result, these rounds have the stopwatch outcome. Is this the expect behavior of the api?

For example:
https://www.hltv.org/stats/matches/mapstatsid/90926/natus-vincere-vs-cr4zy

Api result - The round with 11-14 doesnt show up.
  { outcome: 'ct_win', score: '11-13', ctTeam: 10150, tTeam: 4608 },
     { outcome: 'ct_win', score: '11-15', ctTeam: 10150, tTeam: 4608 },

Thanks!

**Comment by gigobyte** [comment]
> Is this the expect behavior of the api?
Nope, it's just that this outcome was not accounted for. This library reverse engineers the whole HLTV UI so it's normal that things get missed. Thanks for reporting this issue, I'll try to fix it soon 😄

**Comment by gigobyte** [comment]
Fixed in 2.16.2
