### ISSUE TITLE
Convert response to JSON

### ISSUE THREAD

**Issue by maciejbuchert** [gigobyte/HLTV#20]
Hello. I want to convert response to JSON - comfortable for http server in NodeJS. How can I do it ?

**Comment by gigobyte** [comment]
Short answer: Check out the README of this repo, there is an example for every method.

Long answer: Each method returns a [Promise ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)object. To extract the value from that promise you need to use `then` like in the README or async/await.

**Comment by grandprixgp** [comment]
`HLTV.getMatches().then(data => {
            console.log(JSON.stringify(data));
        });`

**Comment by gigobyte** [comment]
What is the problem with this snippet?
