### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by mohitook** [gigobyte/HLTV#21]
Hello,

I just wanted to try your api, but unfortunately I got this error:
`Fetch API cannot load http://www.hltv.org/matches. Redirect from 'http://www.hltv.org/matches' to 'https://www.hltv.org/matches' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Anything what could help?
Thanks!

**Comment by gigobyte** [comment]
I suppose you are trying to run this package in a web browser. Unfortunately, servers have a protection from that and most websites won't allow you to send cross-origin requests.

**Comment by mohitook** [comment]
uh. sorry, I was really tired when this error came... In this case I should use this from a backend..

**Comment by benwck** [comment]
Hello,
Sorry for such an idiot question but, it means you can't use it in angular2 app ?
Thanks,
Ben

**Comment by gigobyte** [comment]
You can't use it in any browser app because of CORS.

**Comment by amaraa019** [comment]
what is efficient way to send socket score log data to client side? Can you explain if you have solution?

**Comment by gigobyte** [comment]
You can use a websocket connection just like HLTV does.
