### ISSUE TITLE
Add id for TeamStats 

### ISSUE THREAD

**Issue by Gaserd** [gigobyte/HLTV#213]
Hey, gigobyte!

What do you think about adding some ids for team stats ? (request getTeamStats)

– match id in matches needs from getting more information about the match.

Example:
```
{
...
matches : [
dateApproximate: 1572210000000
enemyTeam: {id: 8637, name: "Sprout"}
event: {id: 4826, name: "European Champions Cup"}
map: "ovp"
result: "16 - 4",
id : <- need id hear
]
...
}
```

or maybe we added more information about match immediately?

**Comment by gigobyte** [comment]
Available in the newest version.
