### ISSUE TITLE
Livematches

### ISSUE THREAD

**Issue by maciejbuchert** [gigobyte/HLTV#231]
Can you add date for live matches?

**Comment by gigobyte** [comment]
That's not possible because the date is not shown anywhere on the page.

**Comment by maciejbuchert** [comment]
https://www.hltv.org/matches/2338690/unique-vs-nemiga-lbet-invitational-2 here is live match. Date and time is visible.
![image](https://user-images.githubusercontent.com/9607667/71323402-f7f54580-24d2-11ea-82c3-7929f046ef88.png)

**Comment by gigobyte** [comment]
If you are talking about a single match then you can get the date:
`HLTV.getMatch({ id: 2338690 })`
and you'll get an object with a date property:
```js
{
  id: 2338690,
  statsId: undefined,
  team1: { name: 'Unique', id: 9287 },
  team2: { name: 'Nemiga', id: 7969 },
  winnerTeam: undefined,
  date: 1577023500000,
  format: 'Best of 3',
  // ....
}
```

If you are talking about `getMatches` then as you can see there is no date on the matches page:
![image](https://user-images.githubusercontent.com/8791446/71323652-1d3b8100-24de-11ea-98e7-ebd532fd2488.png)
