### ISSUE TITLE
Possible to get Stats/Matches/Etc for a teams current lineup only?

### ISSUE THREAD

**Issue by dbalders** [gigobyte/HLTV#239]
Hey,

Is it possible to get the stats and match history and what not for a teams current lineup? Kinda how now on hltv, you can go to a team's page, and where it shows their current lineup, click on 'Replace context with lineup' and then browse their history, stats, etc based just on the current 5 man roster. 

Thanks,
David

**Comment by gigobyte** [comment]
That's not possible currently, I'll treat this issue as a feature request.

**Comment by dbalders** [comment]
Kk, thanks @gigobyte! Thank you for making this. Is really useful. No pressure to add this feature. Would be useful for me, but I am very thankful for what you have done already.

**Comment by dbalders** [comment]
Hey @gigobyte, I was thinking about this again, and was looking into it on hltv and in your code. On hltv, it looks like they just add the lineup in params after all the stats url. Like this:

    https://www.hltv.org/stats/lineup?lineup=4954&lineup=7398&lineup=7412&lineup=7592&lineup=9032&minLineupMatch=5

So, I am wondering if you couldn't add a boolean param or something for currentLineup:true/false and then move these couple lines earlier if its true to grab the current lineup id's and then append the id's to the end of the urls (https://github.com/gigobyte/HLTV/blob/27441432d5d672649512cde04c34c13be3e903ab/src/endpoints/getTeamStats.ts#L53-L57)? 

I am not 100% sure if this would work or not, but, thought I might try to help if I could as I would still love this feature. Thanks for your time.

**Comment by gigobyte** [comment]
That sounds fine, I don't have free time to work on this. Feel free to add whatever you feel like to the library, I'll make sure you get a quick review :)

**Comment by dbalders** [comment]
I have never used TypeScript before, so, sorry in advance if the code isn't optimized or in the format that it should be. But, I submitted a PR that is working locally for me.
