### ISSUE TITLE
Connect to scorebot via proxy

### ISSUE THREAD

**Issue by Samuron** [gigobyte/HLTV#243]
Hi! Thank you very much for your work.

Is it possible to connect to scorebot via proxy? The `loadPage` seems to only affect loading and parsing the url for the scorebot to connect to.

If not, can you conider an API change to accept `agent` as part of `HLTVConfig`?
It then can be used in `defaultLoadPage`
```javascript
const defaultLoadPage = (url) => {
    return new Promise(resolve => {
        request.get(url, { gzip: true, agent: proxy }, (_, __, body) => resolve(body))
    })
}
```
and in `connectToScorebot`
```javascript
const socket = io.connect(url, {agent: proxy});
```

I can try to come up with a PR to help you with it.

**Comment by gigobyte** [comment]
I haven't worked with http.Agents so I would appreciate your help. My only request is to name the property in the config `httpAgent` so that it's more descriptive than just `agent`.
