### ISSUE TITLE
Odds not selected correctly 

### ISSUE THREAD

**Issue by kairichard** [gigobyte/HLTV#248]
Hi @gigobyte,
thanks for making this. However, I noticed that `getMatch` does not pick up `odds` as seems the markup has changed form `.betting_provider` to just `.provider`.

**Comment by gigobyte** [comment]
Hi, thanks for noticing, you can make a PR fixing this small issue if you want it fixed soon, otherwise I'll probably look into it this weekend.

**Comment by kairichard** [comment]
@gigobyte I added a PR addressing the issue.
