### ISSUE TITLE
getTeam return NaN for player_id if player has no pic

### ISSUE THREAD

**Issue by LaCTuK** [gigobyte/HLTV#253]
**getTeam()** parses profiles pic and getting id from pic url
https://github.com/gigobyte/HLTV/blob/74b52e8ecfb053b96f9719b967a3b8dc4c234016/src/endpoints/getTeam.ts#L37-L43
this method return **NaN** if player's pic is (blankplayer.svg). 

Meanwile **getTeamStats()** using href attribute of player and works like it should (return id)
https://github.com/gigobyte/HLTV/blob/74b52e8ecfb053b96f9719b967a3b8dc4c234016/src/endpoints/getTeamStats.ts#L40-L44

You could test it on teams 8738 (2 guys without pic) / 9253 (full team without pics) / 5290 (full team without pics)

**Comment by gigobyte** [comment]
Thanks, I'll look into it.

**Comment by gigobyte** [comment]
Fixed in `2.18.2`
