### ISSUE TITLE
connectToScoreboard never returns, the promise stays in "pending"

### ISSUE THREAD

**Issue by AlexHill5** [gigobyte/HLTV#29]
console.log(HLTV.default.connectToScorebot( {id: 2314408, onScoreboardUpdate: (data) => {
        console.log(data, 'Flag 1')
    }}) )

This returns = Promise { pending }

I wasn't getting this the other day, it seems like scorebot isn't getting any data to send to me. If I am missing something please lmk

**Comment by gigobyte** [comment]
The `connectToScorebot` method only works through callbacks (`onScoreboardUpdate` and the other). The promise it returns will always be pending because there is nothing to return.

**Comment by AlexHill5** [comment]
HLTV.default.connectToScorebot({id: 2314018, onScoreboardUpdate: (data) => {
        console.log(data)
    }, onLogUpdate: (data) => {
        console.log(data)
    }})

is this correct? I tried to follow the examples, I was using this before and it was working wonderfully. am I missing something?

**Comment by gigobyte** [comment]
Yes, your snippet is correct. I can't tell you why your callbacks are never called, it could be that the match doesn't have a scorebot, I would suggest you use the `onConnect` and `onDisconnect` arguments to check if there is a connection established

**Comment by mintwzy** [comment]
Changing the socket url makes `connectToScorebot` work for me, hope this helps.
```
// const url = $('#scoreboardElement').attr('data-scorebot-url')
const url = 'http://scorebot2.hltv.org:10022';
```
