### ISSUE TITLE
Cannot read property 'split' of undefined inside getMatch.js

### ISSUE THREAD

**Issue by 5ur3** [gigobyte/HLTV#291]
UnhandledPromiseRejectionWarning:`` TypeError: Cannot read property 'split' of undefined
    at /root/my-project/node_modules/hltv/lib/endpoints/getMatch.js:111:29
    at step (/root/my-project/node_modules/hltv/lib/endpoints/getMatch.js:33:23)
    at Object.next (/root/my-project/node_modules/hltv/lib/endpoints/getMatch.js:14:53)
    at fulfilled (/root/my-project/node_modules/hltv/lib/endpoints/getMatch.js:5:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by gigobyte** [comment]
It works fine on my machine, can you give me the match ID you used? Also:
* Make sure that you are not blocked by HLTV;
* Make sure that this is not a problem with your internet connection;
* Make sure that you are passing an existing match ID to the `getMatch` endpoint;

**Comment by 5ur3** [comment]
I read all matches using getMatches method every 100 seconds, and if I need additional info about upcoming or live match I do getMatch method with ID from getMatches result, so ID should be fine. Also I beleive I am not blocked by HLTV because subsequent requests go fine. The issue happens not so often, so next time I catch it i'll provide additional info about the match.

**Comment by 5ur3** [comment]
Before this error occured rarely and it could be fixed with try-catch and requesting match info again after some delay. Now it occures all the time with every existing matchID I try. Every other request (for example getTeam) executes without any errors. Could you please check it again?

**Comment by 5ur3** [comment]
So after about 1 hour of troubles issue was just resolved by itself. I guess for some reason sometimes something get changed on hltv website and it breakes the library, but after some period of time it changes back. How can I help you resolve this issue next time I catch it? Maybe clone some hltv webpages and provide them to you?

**Comment by gigobyte** [comment]
Yes, that would be helpful. It is possible that HLTV temporarily blocks your requests if you send too much, is has happened to me before.

**Comment by chavychaze** [comment]
How often you need to parse data to get blocked?

**Comment by 5ur3** [comment]
I fetch data every 100 seconds, but I don't think I get blocked because I get this error only when calling getMatch, methods like getTeam and others work fine. Also since june 12 I haven't issued this problem so I close this issue until I run into it next time and can provide more useful data to help you fix it.

**Comment by chavychaze** [comment]
thank you, that should save me some time to check when i could be blocked😀 I don't thing i ough to ask this question right here, but as i saw that connectToScorebot is on beta, ar HLTV, mb smone know if there are some changes in data structure, when they make some updates?
