### ISSUE TITLE
getMatch dont works

### ISSUE THREAD

**Issue by Felipevieira2** [gigobyte/HLTV#313]
I'm trying to use the getMatch () function and I have the following error: 

TypeError: Cannot read property 'split' of undefined
>      at C:\Users\User\Documents\dev\react\firebase-server\functions\node_modules\hltv\lib\endpoints\getMatch.js:111:29
>      at step (C:\Users\User\Documents\dev\react\firebase-server\functions\node_modules\hltv\lib\endpoints\getMatch.js:33:23)
>      at Object.next (C:\Users\User\Documents\dev\react\firebase-server\functions\node_modules\hltv\lib\endpoints\getMatch.js:14:53)
>      at fulfilled (C:\Users\User\Documents\dev\react\firebase-server\functions\node_modules\hltv\lib\endpoints\getMatch.js:5:58)
>      at process._tickCallback (internal/process/next_tick.js:68:7)

some classes may have changed on the matches page.

**Comment by gigobyte** [comment]
The tests work fine, can you post the match ID?

**Comment by Felipevieira2** [comment]
after a new test, I identified that the error is no longer occurring
