### ISSUE TITLE
getMatch odds are given twice

### ISSUE THREAD

**Issue by rabidus** [gigobyte/HLTV#317]
For example in this match there are every provider given twice. In real there are only 16 providers, but JSON is provided with 32 providers.

`{"id":"2342969","team1":{"name":"RED Canids","id":7176},"team2":{"name":"Bravos","id":10605},"date":1596139200000,"format":"Best of 1","additionalInfo":"* Group B opening match","event":{"name":"Gamers Club Masters V","id":5183},"maps":[{"name":"tba"}],"players":{"team1":[{"name":"DeStiNy","id":9483},{"name":"KHTEX","id":10842},{"name":"nython","id":18743},{"name":"latto","id":19045},{"name":"heat","id":19046}],"team2":[{"name":"WOOD7","id":14390},{"name":"kaiG","id":14445},{"name":"krg","id":15920},{"name":"danoco","id":16814},{"name":"lealziNho","id":19275}]},"streams":[{"name":"HLTV Live","link":"/live?matchId=2342969","viewers":0}],"live":false,"status":"Scheduled","hasScorebot":false,"headToHead":[{"date":1587424916000,"map":"ovp","winner":{"name":"Bravos","id":10605},"event":{"name":"CLUTCH Season 2","id":5182},"result":"9 - 16"},{"date":1587424916000,"map":"trn","winner":{"name":"RED Canids","id":7176},"event":{"name":"CLUTCH Season 2","id":5182},"result":"16 - 13"},{"date":1581737862000,"map":"d2","winner":{"name":"RED Canids","id":7176},"event":{"name":"Americas Minor South America Open Qualifier 2 - ESL One Rio 2020","id":5172},"result":"16 - 6"},{"date":1580702424000,"map":"nuke","winner":{"name":"RED Canids","id":7176},"event":{"name":"Americas Minor South America Open Qualifier 1 - ESL One Rio 2020","id":5171},"result":"16 - 14"}],"vetoes":[],"highlights":[],"demos":[],"odds":[{"provider":"gv4nx914","team1":1.69,"team2":2.11},{"provider":"p2g0jzml","team1":1.7,"team2":2.05},{"provider":"nz6cnayl","team1":1.64,"team2":2.17},{"provider":"thunderpick","team1":1.62,"team2":2.2},{"provider":"3etkx6rj","team1":1.61,"team2":2.2},{"provider":"5i4rhap1","team1":1.64,"team2":2.19},{"provider":"pinnacle","team1":1.69,"team2":2.09},{"provider":"buff88","team1":1.64,"team2":2.09},{"provider":"vz0pxwkq","team1":1.59,"team2":2.25},{"provider":"unikrn","team1":1.61,"team2":2.2},{"provider":"uazy6czn","team1":1.64,"team2":2.19},{"provider":"cyberbet","team1":1.68,"team2":2.11},{"provider":"sFaLXv3p","team1":1.6,"team2":2.25},{"provider":"vulkan","team1":1.69,"team2":2.11},{"provider":"luckbox","team1":1.66,"team2":2.06},{"provider":"midnite","team1":1.63,"team2":2.14},{"provider":"gv4nx914","team1":1.69,"team2":2.11},{"provider":"p2g0jzml","team1":1.7,"team2":2.05},{"provider":"nz6cnayl","team1":1.64,"team2":2.17},{"provider":"thunderpick","team1":1.62,"team2":2.2},{"provider":"3etkx6rj","team1":1.61,"team2":2.2},{"provider":"5i4rhap1","team1":1.64,"team2":2.19},{"provider":"pinnacle","team1":1.69,"team2":2.09},{"provider":"buff88","team1":1.64,"team2":2.09},{"provider":"vz0pxwkq","team1":1.59,"team2":2.25},{"provider":"unikrn","team1":1.61,"team2":2.2},{"provider":"uazy6czn","team1":1.64,"team2":2.19},{"provider":"cyberbet","team1":1.68,"team2":2.11},{"provider":"sFaLXv3p","team1":1.6,"team2":2.25},{"provider":"vulkan","team1":1.69,"team2":2.11},{"provider":"luckbox","team1":1.66,"team2":2.06},{"provider":"midnite","team1":1.63,"team2":2.14}]}`

**Comment by gigobyte** [comment]
Fixed in `2.20.1`
