### ISSUE TITLE
getMatch() returns "Cannot read property 'split' of undefined"

### ISSUE THREAD

**Issue by LaCTuK** [gigobyte/HLTV#320]
Looks like HLTV broke something again. Get same error on 2 servers
Tryed with matches 
2343255
2343254
Error: 
(node:12612) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at C:\Users\lactu_000\Desktop\HLTV-test\node_modules\hltv\lib\endpoints\getMatch.js:96:93
    at step (C:\Users\lactu_000\Desktop\HLTV-test\node_modules\hltv\lib\endpoints\getMatch.js:33:23)
    at Object.next (C:\Users\lactu_000\Desktop\HLTV-test\node_modules\hltv\lib\endpoints\getMatch.js:14:53)
    at fulfilled (C:\Users\lactu_000\Desktop\HLTV-test\node_modules\hltv\lib\endpoints\getMatch.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by petz15** [comment]
Might it be cloudflare? When I run a getMatch for one single matchid, it works just fine. When I run a batch of multiple Matchids, it gives me the same errors as it does for you but when I try the single matchid again, it then suddenly gives me the error. As soon as I change my connections with a VPN, the single matchid works again.

**Comment by axelmoreen** [comment]
I am getting the same error, and it's definitely cloudfare. When I go to the endpoint: "https://www.hltv.org/matches/ID_HERE/-" I get a cloudfare error 1015: "You are being rate limited":
![image](https://user-images.githubusercontent.com/16216664/90348142-1d066d80-dffa-11ea-9e4f-22737399b3f7.png)

**Comment by LaCTuK** [comment]
Looks like you are right. This error disappeared by itself after some time.
