### ISSUE TITLE
Add starting page to getResults

### ISSUE THREAD

**Issue by MarianoMolina** [gigobyte/HLTV#327]
As far as I can see, right now if I want to get old results (say from page 250) I need to do something like: 

HLTV.getResults({pages: 250}).then((res) => {
  ...
})
Which brings every page from 1 to 250. Would it be possible to change that to start and end page so that if I want to get older results I can? Something like: 

HLTV.getResults({startPage: 240, endPage:250}).then((res) => {
  ...
})

Mostly as a way of not adding useless requests to HLTV's traffic.

**Comment by gigobyte** [comment]
Done.
