### ISSUE TITLE
Is getMatches not working?

### ISSUE THREAD

**Issue by MarianoMolina** [gigobyte/HLTV#329]
Ran this code: 

```
HLTV.getMatches().then((res) => {
  console.log(res)
})
```

And got an empty array. Other methods are working fine.

**Comment by gigobyte** [comment]
The tests are passing fine.

**Comment by MarianoMolina** [comment]
Hey, 
Can you share what exactly your test looks like? Every other method works fine for me, not sure why this instance is not. 

Thanks

**Comment by gigobyte** [comment]
The tests are in the [repo](https://github.com/gigobyte/HLTV/tree/master/__tests__), you can also run them on your machine with `npm run test`
