### ISSUE TITLE
getTeamStats looking at the wrong endpoint

### ISSUE THREAD

**Issue by hipstertwix** [gigobyte/HLTV#331]
endpoint is of the form: `${config.hltvUrl}/stats/teams/${id}/-`
this looks at a 404 page

need to look at : `${config.hltvUrl}/stats/teams/${id}/${teamName}/-`

https://www.hltv.org/stats/teams/8513/Windigo **works**
but 
https://www.hltv.org/stats/teams/8513 **doesn't**

Should be an easy fix!

**Comment by hipstertwix** [comment]
in [https://github.com/gigobyte/HLTV/blob/master/src/endpoints/getTeamStats.ts](getTeamStats.ts)

**Comment by gigobyte** [comment]
https://www.hltv.org/stats/teams/8513/- does work though, the `/-` at the end is hack I found out to get the team page without knowing the team name.
