### ISSUE TITLE
No Team id more

### ISSUE THREAD

**Issue by Helpi90** [gigobyte/HLTV#334]
Since one hour, the most teams are not having an id. I think hltv is changing the source links for the logo.

Example for match id 2344077(from www.hltv.org/matches):

_Team Newhappy_  
..`<img alt="Newhappy" src="https://static.hltv.org/images/team/logo/10839" class="matchTeamLogo" title="Newhappy"></div>`..
_Team TIGER_
..`<img alt="TIGER" src="https://img-cdn.hltv.org/teamlogo/2W6o8O7cQbkbpyPtPq3zV-.png?ixlib=java-2.1.0&amp;s=60d6f8be25bdebfc8ada5e5722b3a0dc" class="matchTeamLogo" title="TIGER"></div>`..

Output:
```
id: 2344077,
    date: 1600761600000,
    team1: { name: 'Newhappy', id: 10839 },
    team2: { name: 'TIGER', id: undefined },
    format: 'bo3',
    title: undefined,
    event: { name: 'FunSpark ULTI 2020 Asia Qualifier', id: 5461 },
    stars: 0,
    live: false },
```
Other Matches:
```
id: 2343652,
    date: 1600794000000,
    team1: { name: 'Evil Geniuses', id: undefined },
    team2: { name: 'Liquid', id: undefined },
    format: 'bo3',
    title: undefined,
    event: { name: 'ESL Pro League Season 12 North America', id: 5495 },
    stars: 3,
    live: false },
  { id: 2343653,
    date: 1600794000000,
    team1: { name: 'Gen.G', id: undefined },
    team2: { name: 'Cloud9', id: undefined },
    format: 'bo3',
    title: undefined,
    event: { name: 'ESL Pro League Season 12 North America', id: 5495 },
    stars: 1,
    live: false },
  { id: 2343715,
    date: 1600794000000,
    team1: { name: 'FURIA', id: undefined },
    team2: { name: 'Chaos', id: undefined },
    format: 'bo3',
    title: undefined,
    event: { name: 'ESL Pro League Season 12 North America', id: 5495 },
    stars: 1,
    live: false },
  { id: 2343716,
    date: 1600794000000,
    team1: { name: '100 Thieves', id: undefined },
    team2: { name: 'Triumph', id: undefined },
    format: 'bo3',
    title: undefined,
    event: { name: 'ESL Pro League Season 12 North America', id: 5495 },
    stars: 1,
    live: false },
  { id: 2343838,
    date: 1600795800000,
    team1: { name: 'sAw', id: undefined },
    team2: { name: 'Singularity', id: undefined },
    format: 'bo1',
    title: undefined,
    event: { name: 'ESEA MDL Season 35 Europe', id: 5494 },
    stars: 0,
    live: false },
  { 
```

**Comment by gigobyte** [comment]
This could mean that the library can no longer return the team ID. :anguished:

**Comment by Helpi90** [comment]
yeah, i need this to show the logo from the teams on my mirror

**Comment by MarianoMolina** [comment]
Same thing is happening to me with 2343665

**Comment by Helpi90** [comment]
Or when the team id isn't important for you, could you add the logo image link to the team object? I added and tested it locally for getMatches/getResults, but i need it over npm for my mirror.

**Comment by Azhrak** [comment]
Team id fix available here:
https://github.com/gigobyte/HLTV/pull/335

**Comment by gigobyte** [comment]
After looking through the DOM I found the root match element that contains the team IDs, which means that this issue is fixable :relieved:

![image](https://user-images.githubusercontent.com/8791446/93311725-04fb5700-f80f-11ea-894f-bdc6c909443a.png)

**Comment by MarianoMolina** [comment]
Hey, sorry to bother, I realize this might sound silly, but just to understand: Is the plan to fix this? 

Not super experienced with stuff like this so just wondering if you could clarify. Also, if you have some idea of timelines, that would be great. Just want to understand! 

Thanks for all the work you do!

**Comment by JuhoNieminen** [comment]
@MarianoMolina as you can see in the pull request page, it says "Pull request successfully merged and closed".
The fix is in and there is already a new version released https://github.com/gigobyte/HLTV/releases/tag/v2.20.3 with this fix in,
You should now be able to get the team id from match pages with the newest version.

**Comment by MarianoMolina** [comment]
Oh, my bad. I hadn't updated the package correctly. 

However, while getMatch now has the team ids, getResults doesn't. Should I open a different thread?

**Comment by Helpi90** [comment]
#336

**Comment by gigobyte** [comment]
@MarianoMolina `getResults` can't have a team id unfortunately. I couldn't find anything anywhere on the page where I could extract the IDs from. @Helpi90 made a PR where we replaces the id with the logo so at least there's an alternative.
