### ISSUE TITLE
Approach to work around getResults missing teamId

### ISSUE THREAD

**Issue by MarianoMolina** [gigobyte/HLTV#338]
Hey, 

So recently there was a change in the DOM of the results page, and now Team ID is not available. This is an issue to me, and it might be an issue to others. 
I did some testing with a sample of results from early 2018 to sept-2020 and these are the results: 
- Unique team names: 2270
- Unique team IDs: 2322
- Difference: 52 more IDs
- Number of teams that have the same name but different IDs: 46

You can see a list of the 46 teams here: 
[
  'ETHEREAL',      'Akatsuki',   'NOORG',
  'Heretics',      'FURY',       'Fearow',
  'Phoenix',       'Entry',      'OG',
  'Legion',        'Revolution', 'Lowkey',
  'Berzerk',       'NONAME',     'Avengers',
  'LOG',           'EXEC',       'HWML',
  'Infamous',      'Orion',      'eXtreme',
  'Duck Nutz',     'Wild',       'Dynasty',
  'Instinct',      'Epsilon',    'Legacy',
  'Fusion',        'Uruguay',    'FATE',
  'Made in Canil', 'Invictus',   '5POWER',
  'Horus',         'Imperial',   'Gorilla Gang',
  'Team n0thing',  'UP',         'Devious',
  'Ignite',        'Titan',      'Levitate',
  'HEY',           'Blink',      'Eclipse',
  'Vexed'
]

Mostly very small teams, with the biggest issue being OG (Ukranian OG: https://www.hltv.org/team/10411/og)

I imagine other people are interested in matching results to the correct teams, and the lack of ID might throw a wrench on your work. 

My question is: Any thoughts on approaches to work around this?

**Comment by gigobyte** [comment]
The problem is that maintaining an internal DB of team IDs is not practical, there are new teams almost every day and if the DB is embedded into the library there would have to be a new release all the time. If the DB is not in the library though, I don't want to invest the time and resources to host a server for this library to function.

**Comment by MarianoMolina** [comment]
Hey @gigobyte. That makes sense. I'm not suggesting you do that. I'm just posting the question to everyone to see what work around people would suggest, if any. 

At any rate, even if you had that database which is something I can do on my own, how would you know which id to assign to a team that has potentially several? The logo link?

**Comment by gigobyte** [comment]
I believe the approach with the least amount of extra requests would be to get the earliest date from the results headers (I mean the headers in the format `Results for September 13th 2020`, the earliest one is at the bottom of the page) and load the stats from today to that date (in this case `https://www.hltv.org/stats/matches?startDate=2020-09-13&endDate=2020-09-17`) and get the IDs from there.

The other option is to pretty much deprecate `getResults`, it has 99% the same information as `getMatchesStats`

**Comment by MarianoMolina** [comment]
After thinking about it for a bit, I think getMatchesStats will be the way to go for me. I will need to convert the map results to match results since that is what I am working with. The only valuable data getResults provides at this point is the match id, which is a minor aspect. 

While I have you here, I am looking for a way of assessing how long the lineup has been together, i.e. dates of all lineup changes like this: https://www.hltv.org/stats/teams/lineups/9565/Vitality

Do you know if there are any ways of getting this with the api? Or would this require a new feature?

**Comment by gigobyte** [comment]
> Do you know if there are any ways of getting this with the api?
You can't get that info currently.
