### ISSUE TITLE
getMatch error

### ISSUE THREAD

**Issue by Felipevieira2** [gigobyte/HLTV#354]
Hello, I'm trying to get match data: 2344827 and I'm getting a split error

my code: 
`let match = null; 

	await HLTV.getMatch({id: 2344827}).then( res => {
		match = res;
	}).catch((error) => {
        console.error(error);
    });	
	console.log( match );`

**Comment by gigobyte** [comment]
Looks like HLTV changed the link for the placeholder team image. Here is the link to the match: https://www.hltv.org/matches/2344827/-

You can either wait for someone to fix it or you can make a PR changing this piece of code: https://github.com/gigobyte/HLTV/blob/master/src/endpoints/getMatch.ts#L66
