### ISSUE TITLE
v2.22.0 has no lib dir published

### ISSUE THREAD

**Issue by ncla** [gigobyte/HLTV#378]
`yarn add hltv@2.22.0 `

![image](https://user-images.githubusercontent.com/5507083/104845164-9e7d6700-58dc-11eb-9c18-dd2ebfdbdb90.png)

**Comment by samnewhouse** [comment]
Having the same issue, can confirm 2.21.1 has the lib directory.

**Comment by gigobyte** [comment]
Sorry for the bad release, I've published it correctly this time as `2.22.1`
