### ISSUE TITLE
incompatible with hltv-api

### ISSUE THREAD

**Issue by Revilum** [gigobyte/HLTV#388]
Hi,
I was using [this ](https://github.com/dajk/hltv-api) api to get hltv stats but it had some missing features which is why I wanted to include this api to "extend" its functionality. I managed to get an webserver running with one api but when including the second one I have the following issue: `SyntaxError: Identifier 'HLTV' has already been declared`
The Problem is that both modules require to include it with the const name hltv. Is there any way to change the identifier of the api?

the error can be treiggered when visiting localhost:3000/ranking

my code:
```
const HLTV = require('hltv-api').default
const express = require('express')
const { HLTV } = require('hltv')
const app = express()
//this API (trying to host the ranking on localhost:3000/ranking
app.get('/ranking', async (req, res) => {
  const ranking = await HLTV.getTeamRanking()
  res.send(ranking)
})
// the other api. All links work
app.get('/news', async (req, res) => {
  const news = await HLTV.getNews()
  res.json(news)
})

app.get('/results', async (req, res) => {
  const results = await HLTV.getResults()
  res.json(results)
})

app.get('/matches', async (req, res) => {
  const matches = await HLTV.getMatches()
  res.json(stats)
})

app.get('/:matchId(*)', async (req, res) => {
  const stats = await HLTV.getMatches(req.params.matchId)
  res.json(stats)
})

app.listen(3000, () => {
  console.log('Listening on port 3000...')
})

```

**Comment by gigobyte** [comment]
Sure, just import it under a different name:
```ts
const HLTVApi = require('hltv-api').default
```
or
```ts
const { HLTV: HLTVWhaterverYouWant } = require('hltv')
```

**Comment by Revilum** [comment]
thanks
