### ISSUE TITLE
getPlayerRanking() returning empty JSON

### ISSUE THREAD

**Issue by Revilum** [gigobyte/HLTV#389]
Hi,
I was trying to host getPlayerRanking() on a website but it seems to be that the JSON is empty
here is my code:
```
const HLTV = require('hltv-api').default
const express = require('express')
const { HLTV: HLTV2 } = require('hltv')
const app = express()
app.get('/playerranking/:startdate/:enddate', async (req, res) => {
  const parameters = new Object()
  parameters.startDate = req.params.startdate
//  parameters.endDate = req.params.enddate
  const playerranking = await HLTV2.getPlayerRanking(parameters)
  console.log(playerranking)
  res.json(playerranking)
})

app.listen(3000, () => {
  console.log('Listening on port 3000...')
})
```
when visiting localhost:3000/playerranking/2018-07-01/2018-10-01 (same dates as in the documentation) HLTV2.getPlayerRanking(parameters) just returns `[]`
when I try just to use HLTV2.getPlayerRanking() then my programm crashes because startDate is missing despite the documentation telling me that it should just return the current ranking.

Revilum

**Comment by gigobyte** [comment]
Fixed.
