### ISSUE TITLE
connectToScorebot doesn't reach onConnect() event

### ISSUE THREAD

**Issue by OfficialLahusa** [gigobyte/HLTV#390]
```js
app.get('/scoreboard/', async (req, res) => {
  var scoreboard = await HLTV2.connectToScorebot({id: 2346334, onScoreboardUpdate: (data, done) => {
    console.log(data)
    console.log("onScoreboardUpdate received")
    }, onLogUpdate: (data, done, ) => {
      console.log(data)
      console.log("onLogUpdate received")
    }, onConnect: (data, done, ) => {
      console.log(data)
      console.log("onConnect received")
    }, onDisconnect: (data, done, ) => {
      console.log(data)
      console.log("onDisconnect received")
    }
  })
  console.log(scoreboard)
  res.json(scoreboard)
  console.log("scoreboard logged")
})
```

Using an ID of a currently running Match on HLTV doesn't give any return value and doesn't fire any of the listed events.

**Comment by gigobyte** [comment]
Which version are you using? Just tried it and it works on the newest version - `2.23.0`.
![image](https://user-images.githubusercontent.com/8791446/107114370-f4a35180-686d-11eb-9e0a-be0e4cd05ed1.png)

**Comment by OfficialLahusa** [comment]
We use version 2.23.0

**Comment by OfficialLahusa** [comment]
Update: When I run the function on the node server I get the following exception:
```
/home/zsunamy/devel-hltv-api/node_modules/hltv/lib/endpoints/connectToScorebot.js:11
            .split(',')
            ^

TypeError: Cannot read property 'split' of undefined
    at /home/zsunamy/devel-hltv-api/node_modules/hltv/lib/endpoints/connectToScorebot.js:11:13
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by gigobyte** [comment]
You are probably being rate limited.

**Comment by Revilum** [comment]
Hi, 
I have the same issue. The only thing I can add is that the index.ts in the github release is different than the index.js and index.d.ts in the npm release. Is there a way to use the github release instead of the npm release or has the code a mistake outside of the scoreBot?
my code: 
```
app.get('/scoreboard/', async (req, res) => {
  HLTV2.connectToScorebot({id: 2346468, onScoreboardUpdate: (data, done) => {
    console.log(data)
    console.log("onScoreboardUpdate received")
    }, onLogUpdate: (data, done, ) => {
      console.log("onLogUpdate received")
      console.dir(data)
    }, onConnect: (data, done, ) => {
      console.log("onConnect received")
      console.dir(data)
    }, onDisconnect: (data, done, ) => {
      console.log("onDisconnect received")
      console.dir(data)
    }
  })
```

**Comment by gigobyte** [comment]
I'm sorry guys, the issue is definitely on your side. Try deleting node_modules and running install again, you're probably on an old version. I made a folder with only hltv installed and it worked:
![image](https://user-images.githubusercontent.com/8791446/107117845-bd409f00-6885-11eb-8f3c-aa7b3778e29f.png)

**Comment by Revilum** [comment]
thanks for your answer.
I was able to fix it by downgrading nodejs to v12. the log was empty when using v15. I hope that's also your issue @OfficialLahusa 

Thanks again for your support and fast answers!

**Comment by OfficialLahusa** [comment]
Downgrading node.js did infact fix the issue, thanks to both of you!

**Comment by gigobyte** [comment]
For anyone else reading this issue, I'm using node `15.2.1` and it still works.

**Comment by Revilum** [comment]
interesting node v15 didn't work for me. Maybe it's because se I'm running the api with the linux version of node.
