### ISSUE TITLE
getPlayerByName crashes application when invalid name is given

### ISSUE THREAD

**Issue by Revilum** [gigobyte/HLTV#391]
Hi,
I have the issue that my application crashes when I use getPlayerByName() with a name that doesn't exist
when I run `nodejs index.js`:
```
(node:4855) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at /home/zsunamy/hltv-api/node_modules/hltv/lib/endpoints/getPlayerByName.js:53:76
    at step (/home/zsunamy/hltv-api/node_modules/hltv/lib/endpoints/getPlayerByName.js:33:23)
    at Object.next (/home/zsunamy/hltv-api/node_modules/hltv/lib/endpoints/getPlayerByName.js:14:53)
    at fulfilled (/home/zsunamy/hltv-api/node_modules/hltv/lib/endpoints/getPlayerByName.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4855) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
when I run `nodejs --unhandled-rejections=strict index.js`:
```
/home/zsunamy/hltv-api/node_modules/hltv/lib/endpoints/getPlayerByName.js:53
                    return [2, index_1.default.getPlayer({ id: firstResult.id })];
                                                                           ^

TypeError: Cannot read property 'id' of undefined
    at /home/zsunamy/hltv-api/node_modules/hltv/lib/endpoints/getPlayerByName.js:53:76
    at step (/home/zsunamy/hltv-api/node_modules/hltv/lib/endpoints/getPlayerByName.js:33:23)
    at Object.next (/home/zsunamy/hltv-api/node_modules/hltv/lib/endpoints/getPlayerByName.js:14:53)
    at fulfilled (/home/zsunamy/hltv-api/node_modules/hltv/lib/endpoints/getPlayerByName.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by gigobyte** [comment]
What would you expect the behaviour to be? I can throw a pretty error but the promise will be rejected either way.

**Comment by Revilum** [comment]
yes that would be good because using this API for a webserver so one request could crash the entire API which wouldn't be good.
Returning nothing should be enough for that as long as it doesn't crash.

thanks again for all your help!

**Comment by gigobyte** [comment]
It shouldn't crash your entire API, `getPlayerByName` returns a promise, you are probably using async/await and not catching the error. Returning `undefined`/`null` doesn't make sense when the return type is Promise. If there is an error the promise will be rejected and you'll be able to call `.catch(err => ...)` on it.

**Comment by gigobyte** [comment]
I've added a pretty error, but if you're not handling it it's still going to crash your application.

**Comment by barbozafernando** [comment]
Hey @Revilum, if you really wanna use async/await, dont forget to use try/catch to handle the errors, so your application wont crash it.

**Comment by Revilum** [comment]
> Hey @Revilum, if you really wanna use async/await, dont forget to use try/catch to handle the errors, so your application wont crash anymore.

thanks for you help!
I don'T know much about nodejs so I have to look into what and when try/catch does and is does exactly.
