### ISSUE TITLE
getMatchStats() doesn't work for matches with ID's higher than 66998

### ISSUE THREAD

**Issue by Revilum** [gigobyte/HLTV#394]
Hi,
It seems like that HLTV changed its ID system to a 7-digit number but getMatchStats() only works for the old 5-digit ID.
when I use the new 7-digit ID I get the following error:
```
(node:19342) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at /home/zsunamy/steelapi/node_modules/hltv/lib/endpoints/getMatchStats.js:85:76
    at step (/home/zsunamy/steelapi/node_modules/hltv/lib/endpoints/getMatchStats.js:44:23)
    at Object.next (/home/zsunamy/steelapi/node_modules/hltv/lib/endpoints/getMatchStats.js:25:53)
    at fulfilled (/home/zsunamy/steelapi/node_modules/hltv/lib/endpoints/getMatchStats.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:19342) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by gigobyte** [comment]
What do you mean "7-digit ID system", the IDs HLTV uses are autoincrementing. The latest match stats page has an ID of `114902`, the next one will be `114903` and so on.

**Comment by gigobyte** [comment]
What do you  mean "7-digit system", HLTV uses incrementing IDs for their stats, the latest match has an stats ID of  [79170](https://www.hltv.org/stats/matches/79170/forze-vs-lyngby-vikings), the next one will be 79171, then 79172 etc.

Can you link me a 7-digit ID?

**Comment by gigobyte** [comment]
I see that you've written that it doesn't work with IDs higher than 66998, that's not true. 66999 doesn't work, but that's because they've probably deleted it, they input the matches manually so sometimes there's a mistake and they delete pages. [70000](https://www.hltv.org/stats/matches/70000/forze-vs-lyngby-vikings) exists and it's working.

**Comment by Revilum** [comment]
oh now I get it. There are 2 different IDs fort stats and results. i didn't know that. Apparently I didn'T see the statside in getMatch() and thought it was the same.
Thanks!
