### ISSUE TITLE
implement getTeamByName

### ISSUE THREAD

**Issue by Drachenfalke12** [gigobyte/HLTV#398]
Hey,
I've created a new function getting a team by its name, but I don't know how to push it to GitHub, because the .js files in your repository are missing.

**Comment by gigobyte** [comment]
That is because this project is written in TypeScript :)

**Comment by Drachenfalke12** [comment]
Yeah, I know, but how can I add a function?

**Comment by Drachenfalke12** [comment]
added those functions see #401
