### ISSUE TITLE
getTeam({id}) Failing

### ISSUE THREAD

**Issue by Jerryshan09** [gigobyte/HLTV#402]
getTeam appears to return an unhandled promise rejection for a majority of team ids, with the same team ids having no issue with getTeamStats: ex. team id 10842.

**Comment by Revilum** [comment]
https://hltv-api-steel.vercel.app/api/team/10842 works for me.

**Comment by gigobyte** [comment]
Can you log the exception? If the error is `"Access denied"` then you just got rate limited.
