### ISSUE TITLE
getEvent doesn't work on specific event

### ISSUE THREAD

**Issue by AdamBobocky** [gigobyte/HLTV#406]
(node:2496) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at C:\app\node_modules\hltv\lib\endpoints\getEvent.js:65:76

Code:
`import HLTV from 'hltv'`

`;(async () => {`
`  console.log(await HLTV.getEvent({ id: 5630 }))`

`  await new Promise(s => setTimeout(s, 12000))`

`  console.log(await HLTV.getEvent({ id: 5764 }))`
`})()`

ID 5630 is fine, but ID 5764 never works

**Comment by AdamBobocky** [comment]
And it doesnt work with getEventByName either, it throws the same error. The event in question is: https://www.hltv.org/events/5764/pinnacle-cup-2021

**Comment by gigobyte** [comment]
The error is because there are "TBD teams", I'll push a fix soon.
