### ISSUE TITLE
[Bug] - HLTV.getPlayer()

### ISSUE THREAD

**Issue by lucaspalencia** [gigobyte/HLTV#41]
`HLTV.getPlayer({id: 429})`
It's Karrigan player ID (https://www.hltv.org/stats/players/429/karrigan)

**Error:**
`Cannot read property '0' of null at Object.<anonymous>(node_modules/hltv/lib/endpoints/getPlayer.js:51:65)`

**Comment by gigobyte** [comment]
This issue is fixed in v.2.7.0
