### ISSUE TITLE
Tests seem to fail

### ISSUE THREAD

**Issue by MonsieurBibo** [gigobyte/HLTV#412]
Hi, when I run `npm run test`, some tests seem to fail.

- I do think HLTV modified its structure, it structures it now in order of IDs' growth.
- Twitter's links now begin with `www.`.
- ChrisJ's clip got deleted from HLTV and from Twitch.

**Comment by gigobyte** [comment]
The tests are there to automate checking if something has changed, that's why they don't run on commit etc

As long as they don't throw exceptions it's fine, I update them from time to time but it's nothing urgent.
