### ISSUE TITLE
Feature Request: Handle 5+ Roster Team Pages

### ISSUE THREAD

**Issue by MonsieurBibo** [gigobyte/HLTV#419]
HLTV recently added Substitutes and Coaches to the team pages. It would be nice if this was implemented in this package.

Coach selector: `.profile-team-stat .a-reset`

Substitute selector: `Substitute` doesn't have a proper selector, but we could use the `.profile-team-stat:nth-child(5)`  or `.profile-team-stat:nth-child(5)` selectors.

However, this could be handled more properly while using the `roster` Tab. It will also give more information like time in the team or status.
![image](https://user-images.githubusercontent.com/47726709/110835019-8d2e5680-829e-11eb-975f-f568fadd9042.png)

If nobody has the time or the inclination, I can try to implement it myself.

Thanks.

**Comment by MonsieurBibo** [comment]
In order to implement it, I would like to know something. Should I create a new interface for teams and players OR use the full versions? I don't think using the full interfaces is a good idea, as it will cause confusion when the full interfaces are returned without all the information (Twitter, Instagram, etc.).

**Comment by gigobyte** [comment]
@MonsieurBibo Features are frozen in v2, I'm currently rewriting the whole library (track progress [here](https://github.com/gigobyte/HLTV/pull/422)). Please don't make merge requests for now.

**Comment by MonsieurBibo** [comment]
@gigobyte no problem, I'll wait whether V3 is release or more advanced to make PRs.

**Comment by gigobyte** [comment]
Done in v3!
