### ISSUE TITLE
Package size

### ISSUE THREAD

**Issue by MonsieurBibo** [gigobyte/HLTV#424]
Bundlephobia.com indicates that user-agents package has quadrupled the size of the library.

![image](https://user-images.githubusercontent.com/47726709/110997696-123c6d00-837e-11eb-9877-2f66db58aead.png)

Does it worth it ?

**Comment by gigobyte** [comment]
Ah, crap, didn't notice that. With the random user agent you can make a lot more requests per minute, I actually didn't get rate limited even when spamming with requests (but I wouldn't test my luck).

**Comment by MonsieurBibo** [comment]
Maybe [this library](https://github.com/skratchdot/random-useragent) will make the job ?
