### ISSUE TITLE
GetMatchMapStats occaisionally not working since 2.23.0

### ISSUE THREAD

**Issue by jamesNWT** [gigobyte/HLTV#428]
While using version 2.25.1 I am occaisionally and seemingly randomly getting this error from HLTV.getMatchMapStats:

`TypeError: Cannot read property 'split' of undefined
`    

this is coming up in my console from a simple catch(err){console.log(err);} block.

```
TypeError: Cannot read property 'split' of undefined
at /path_to_my_project/node_modules/hltv/lib/endpoints/getMatchMapStats.js:93:77
    at step (/path_to_my_project/node_modules/hltv/lib/endpoints/getMatchMapStats.js:44:23)
    at Object.next (/path_to_my_project/node_modules/hltv/lib/endpoints/getMatchMapStats.js:25:53)
    at fulfilled (/path_to_my_project/node_modules/hltv/lib/endpoints/getMatchMapStats.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```
I was able to fix by downgrading to 2.23.0 (Not sure if that's the last one that didn't have this problem, was just the last one I was using). Not  a huge deal for me but seemed like it should be posted.

Also, after I catch the error I simply try again and it will work on the second try.

**Comment by gigobyte** [comment]
> Also, after I catch the error I simply try again and it will work on the second try.

This means that you're getting temporarily blocked by Cloudflare. Downgrouding didn't actually fix it, it was just that you didn't make a request for some time while you were installing the old version and that removed the throttle limit.

**Comment by jamesNWT** [comment]
I've gotten cloudflare restrictions before and it would be a different error message, the log would say specifically that my access was blocked by cloudflare. In my script I'm making requests every 3.5 seconds, and I never got this error when using 2.23.0, yet was somehow getting it with 2.25.1, all else being equal.

**Comment by gigobyte** [comment]
Strange, but if it was a bug then why would it work the second time?

**Comment by gigobyte** [comment]
Also the last behaviour change made to `getMatchMapStats` was on Oct 15, 2019 (verison 2.16.2)

**Comment by gigobyte** [comment]
I pinpointed the problem - `hltv` makes 2 requests for `getMatchMapStats` but the error handling only works for the first one. So what happens is the first request goes through but the second one gets throttled and you get an error.
