### ISSUE TITLE
Minor Bug: Github pages doesn't like empty row

### ISSUE THREAD

**Issue by MonsieurBibo** [gigobyte/HLTV#436]
![image](https://user-images.githubusercontent.com/47726709/112862740-5b96f700-90b6-11eb-9f2b-88e6dba66e02.png)

 It seems that GH pages can't render properly empty row of a table.

**Comment by gigobyte** [comment]
Renders fine, where are you seeing this? On the main repo page?

![image](https://user-images.githubusercontent.com/8791446/112863423-85085080-90bf-11eb-8e82-6220fedd6246.png)
