### ISSUE TITLE
Minor Bug: ⚠️emoji isn't rendered on GH pages

### ISSUE THREAD

**Issue by MonsieurBibo** [gigobyte/HLTV#437]
# **On the README**
![image](https://user-images.githubusercontent.com/47726709/112863049-ba5c7080-90b6-11eb-8597-61ae1406d028.png)
# **On the site**
![image](https://user-images.githubusercontent.com/47726709/112863089-c3e5d880-90b6-11eb-9d35-c4d02f1423c8.png)

**Comment by gigobyte** [comment]
I didn't even know I had GH pages enabled lol, I don't care much about it.
