### ISSUE TITLE
Feature Request: matchId to getTeam

### ISSUE THREAD

**Issue by Drachenfalke12** [gigobyte/HLTV#441]
Hey,

could you add the upcoming and past matches to the getTeam endpoint? I know something like this is already included in the getTeamStats request, but for our application, it would be quite nice to have [that information](https://www.hltv.org/team/7532/big#tab-matchesBox). It contains past map series and also upcoming matches for a team. It was also included in the last version of your API and I think it was quite useful :) 
Something like [this](https://prnt.sc/111th7y) similar to the last version would be enough. 
Thanks a lot!

**Comment by gigobyte** [comment]
HLTV shows only the latest matches on the `getTeam` page, there's no point in parsing them. You can get the upcoming matches from `getMatches` and the results from `getResults` when it's added.

**Comment by Drachenfalke12** [comment]
Yeah, you're right, that would work for us too.
