### ISSUE TITLE
add additionalInfo to getMatch endpoint

### ISSUE THREAD

**Issue by Drachenfalke12** [gigobyte/HLTV#442]
Hey sorry for bothering you again :)

In your last version of the API you had something like this:

`"format": "Best of 3 (Online)",
  "additionalInfo": "* Group D",
  "event": {
    "name": "ESL Pro League Season 13",
    "id": 5553
  },`

But in the latest versions, this additionalInfo is missing. It would be a very nice feature for us. Thanks for your effort!!!

**Comment by gigobyte** [comment]
It's missing because it's random text. It has all kind of notes, so it doesn't make sense in the context of a CS match, only if you want to make a HLTV clone.

**Comment by Drachenfalke12** [comment]
Hmmm I thought it was showing something like `Lower bracket final` or `Playoffs round 1`, well at least it was some nice extra information on how far the event is

**Comment by gigobyte** [comment]
Usually it does, but it also be a [stream link](https://www.hltv.org/matches/2296144/d13-vs-tcg-funspark-ulti-2021-asia-regional-series-1) or any other [random text](https://www.hltv.org/matches/2299710/d13-vs-tcg-funspark-ulti-2021-asia-regional-series-1) like "[mousesports forfeit the match](https://www.hltv.org/matches/2296544/d13-vs-tcg-funspark-ulti-2021-asia-regional-series-1)"

**Comment by Drachenfalke12** [comment]
Hmm I see thats odd

**Comment by gigobyte** [comment]
I've added it as `significance` and it will only parse info about the match in the tournament (e.g. "Lower bracket final")
