### ISSUE TITLE
getMatchStats issue with 6 man rosters

### ISSUE THREAD

**Issue by Drachenfalke12** [gigobyte/HLTV#443]
Hey,

the endpoint getMatchStats has an issue with 6 man rosters. [This](https://www.hltv.org/matches/2347664/mad-lions-vs-sprout-funspark-ulti-2021-europe-regional-series-1) match had 6 players for MAD Lions, but in the [API request](http://revilum.com:3000/api/matchstats/80328) the sixth player of Mad Lions is detected as the first player of Sprout.

**Comment by Drachenfalke12** [comment]
and another minor thing: Im not quite sure about [this](https://prnt.sc/11334w9) `1` is it a typo?

**Comment by gigobyte** [comment]
Thanks for the report, that is because of this:
```ts
team1: playerOverviewStats.slice(0, 5),
team2: playerOverviewStats.slice(5)
```
the code didn't account more than 5 players.

About the other thing - it's not a typo, if the stats use the Rating 1.0 system the `rating1` property will be populated, if they use Rating 2.0 there will be `rating2` property.

**Comment by Drachenfalke12** [comment]
Ahh okay thanks for your quick reply 👍
