### ISSUE TITLE
reimplement information if an event was featured.

### ISSUE THREAD

**Issue by Revilum** [gigobyte/HLTV#444]
since the release of version 3, there has been less information about events.
new: ```
{
    "id": 5553,
    "name": "ESL Pro League Season 13",
    "dateStart": 1615201200000,
    "dateEnd": 1618135200000
  }
``` old: ```
{
    "name": "ESL Pro League Season 13",
    "id": 5553,
    "dateStart": 1615201200000,
    "dateEnd": 1618135200000,
    "today": true,
    "featured": true
  }
``` For my application the information if an event is featured it pretty important so I took a look at the [site](https://www.hltv.org/events) and found out that all featured events are in the following div container: `<div class="big-events">`

Thanks again for this amazing api!

**Comment by gigobyte** [comment]
So featured are all big events + the ongoing events in the Featured tab, right?

**Comment by Revilum** [comment]
> So featured are all big events + the ongoing events in the Featured tab, right?

Yeah I think so. At least featured events are events with mostly top30 teams competing.
