### ISSUE TITLE
'getResults' returns duplicate matches

### ISSUE THREAD

**Issue by ThomasGiulianelli** [gigobyte/HLTV#45]
hltv.org/results/ has a "featured results" section containing several matches. These matches are also found elsewhere on the page. The [getResults](https://github.com/gigobyte/HLTV#getresults) method returns all matches on the page including those in the "featured results" sections so they appear twice in the array. I believe they should be removed if possible.

**Comment by gigobyte** [comment]
You are correct, thanks for reporting this issue.

**Comment by gigobyte** [comment]
This is fixed as of version 2.7.1
