### ISSUE TITLE
Only doubt(delete after)

### ISSUE THREAD

**Issue by igorgomeslima** [gigobyte/HLTV#467]
Hey @gigobyte nice work here!

You can explain how you can connect to "score bot" and receive info without the "score bot" be a WebSocket Api? Do you know how this works? :)

I'am trying to make the same thing with .NET WebSocket implementation, but without success. 

Cheers.

**Comment by gigobyte** [comment]
HLTV uses socket-io, so that's not possible. You need to connect with a socket-io client otherwise it's not going to work.

**Comment by igorgomeslima** [comment]
@gigobyte, nice... thank you! ;)
