### ISSUE TITLE
Stream link Undefined in getMatch method

### ISSUE THREAD

**Issue by crizhon** [gigobyte/HLTV#47]
The getMatch method are returning link undefined for all streams.

Example:

  HLTV.getMatch({ id: '2319592' }).then(result => {
        console.log(result);
        res.status(200).json(result);
    })

returns

{ team1: { name: 'Liquid', id: 5973 },
  team2: { name: 'eUnited', id: 7106 },
  winnerTeam: undefined,
  date: 1524607200000,
  format: 'Best of 1',
  additionalInfo: '',
  event: { name: 'ECS Season 5 North America', id: 3602 },
  maps: [ { name: 'inf', result: '' } ],
  players: 
   { team1: [ [Object], [Object], [Object], [Object], [Object] ],
     team2: [ [Object], [Object], [Object], [Object], [Object] ] },
  streams: [ { name: 'FACEIT TV', link: undefined, viewers: 7800 } ],
  live: true,
  title: undefined,
  hasScorebot: true,
  highlightedPlayer: { name: 'NAF', id: 8520 },
  headToHead: 
   [ { date: 1499814096000,
       winner: [Object],
       event: [Object],
       map: 'cbl',
       result: '16 - 7' },
     { date: 1499814096000,
       winner: [Object],
       event: [Object],
       map: 'mrg',
       result: '16 - 14' } ],
  vetoes: [],
  highlights: [] }

**Comment by klayveR** [comment]
Temporary fix:

In `node_modules/hltv/lib/endpoints/getMatch.js` (line 90) replace

`link: streamEl.attr('data-stream-embed'),` with  
`link: streamEl.find('.stream-box-embed').attr('data-stream-embed'),`

**Comment by gigobyte** [comment]
This is fixed in version 2.7.2
