### ISSUE TITLE
Get the scorebot data in a single line, readable form

### ISSUE THREAD

**Issue by dadodiciassette** [gigobyte/HLTV#477]
Hi guys sorry if I bother you, I'm not an good at programming but i really like this tool so that's why I'm asking you to help me.
![codice](https://user-images.githubusercontent.com/85746274/122419633-58abf400-cf8b-11eb-8cdc-6cf92e5379ed.PNG)
I made the following code that connects me to a game and sends me back the information as you see in the image.
![Cattura](https://user-images.githubusercontent.com/85746274/122419697-66fa1000-cf8b-11eb-8164-7423256a5863.PNG)
My question is how can I output that data like the real HLTV scorebot (for example only a line with: "EliGE killed falleN with AK47", or "olofmeister disconnected"). Thanks for your help

**Comment by gigobyte** [comment]
You can construct any strings  you want from the `data` object, for example:
```js
onLogUpdate: (data) => {
 const event = Object.keys(data)[0]
 const eventData = data[event]

  if (event === 'Kill') {
      console.log(`${eventData.killerNick} killed ${eventData.victimNick} using ${eventData.weapon}`)
  }
}
``` 
I'll be closing this issue since it's not related to the library at all.
