### ISSUE TITLE
cheerio.Root in scraper.d.ts

### ISSUE THREAD

**Issue by petz15** [gigobyte/HLTV#489]
after updating all packages and dependencies, I am getting an error when compiling. The error occurs in scraper.d.ts, it does not recognize the exported member named 'Root'. This error occurs for line 2 as well as line 29. 

It seems to me, that this is an issue with cheerio.

**Comment by joshuajeschek** [comment]
Did you manage to fix this, and if yes, how?

**Comment by AdamJessop** [comment]
Having this same issue also @petz15 @joshuajeschek did you get a resolution? Appears to be that it needs to be `root` instead of `Root`

**Comment by joshuajeschek** [comment]
I just manually edited the types to get rid of the error, but still don't know why it happens

**Comment by AdamJessop** [comment]
Ah it looks like installing the latest @types/cheerio package on my project appears to have resolved the issue.
