### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by dovydast** [gigobyte/HLTV#49]
Hi, Could you add feature for getMatches() and getResults()  of adding team logos so that i could use it for interpolation

**Comment by dovydast** [comment]
oh i see you have an id for each team, which represents the logo, so i should interpolate just as an id, not like a full url,
<img src="example-hltv-image/{{id}}">

**Comment by gigobyte** [comment]
Another user has already found out how to get the team logos: https://github.com/gigobyte/HLTV/issues/9#issuecomment-320930976
