### ISSUE TITLE
Fix type error Cannot read property 'split' of undefined in getMatchStats

### ISSUE THREAD

**Issue by rafaelvicio** [gigobyte/HLTV#492]
https://www.hltv.org/matches/2350165/mibr-vs-keyd-cbcs-elite-league-2021-season-2

  const stats = await HLTV.getMatchStats({ id: 2350165 });

`TypeError: Cannot read property 'split' of undefined
    at getIdAt (node_modules\hltv\lib\utils.js:93:45)`

**Comment by gigobyte** [comment]
`getMatchStats` requires a match stats ID, not a match ID.
