### ISSUE TITLE
random useragent still causes some requests to be blocked

### ISSUE THREAD

**Issue by Revilum** [gigobyte/HLTV#497]
some useragents are blocked by cloudflare which causes some requests to fail.
According to my rough calculations this is still the case for ~1.5% of all requests, which is still  a lot for my application.
A Solution would be to be able to toggle random useragents so that you can choose between a larger amount of requests per second or a more reliable method which will use the default/one useragent.

**Comment by gigobyte** [comment]
I've removed the random useragent.
