### ISSUE TITLE
Crash with "connectToScorebot"

### ISSUE THREAD

**Issue by IceNdev** [gigobyte/HLTV#50]
I'm using HLTV.connectToScorebot..... to send json data to a webpage, and when i try it i get this error:
![capturar](https://user-images.githubusercontent.com/13720740/40084626-a7fd7eaa-588f-11e8-9b7c-20e4100aa018.PNG)

**Comment by gigobyte** [comment]
I don't think that this is related to the HLTV library. Seems like you're trying to send a response multiple times, which can't work with a endpoint, you should look into websockets.

**Comment by IceNdev** [comment]
Ok i will try it, thank you for the answer.
