### ISSUE TITLE
Add event Filter into getPlayerStats

### ISSUE THREAD

**Issue by kpei** [gigobyte/HLTV#509]
the `event` query param is supported on hltv e.g https://www.hltv.org/stats/players?startDate=2021-09-20&endDate=2021-09-23&event=5605

In addition, it would be nice to retrieve overall stats for an event for all players (like above link)

**Comment by gigobyte** [comment]
@MonsieurBibo Yep, of course.

**Comment by MonsieurBibo** [comment]
FYI, I didn't have much time to look about it recently, however I think I can make the first PR this weekend.

**Comment by guyu818** [comment]
hltv/lib/utils.js:78 throw new Error('Access denied | www.hltv.org used Cloudflare to restrict access');
how to resolve

**Comment by MonsieurBibo** [comment]
Hello @guyu818, I would love to help you but please create your own issue with all details needed (your code, variables + explanation)

Thanks in advance ;)
