### ISSUE TITLE
Improve createInstance 

### ISSUE THREAD

**Issue by mavrick** [gigobyte/HLTV#51]
Improve `createInstance` by allowing an additional object to be passed through to the fetch instance to support custom http headers, http agent and query string parameters.

I'm not up-to-scratch with my typescript - if we add in a `fetchOptions` object to the base `HLTVConfig`
```javascript
export default interface HLTVConfig {
    hltvUrl?: string
    hltvStaticUrl?: string
    fetchOptions?: object
}
```
and then handle that inside `mappers/fetchPage`
```javascript
export const fetchPage = async (url: string) => cheerio.load(await fetch(url, fetchOptions).then((res: any) => res.text()))
```
I think we're in business. 

`fetchOptions` can be an empty object. Then we can pass through headers like `user-agent`, `host`, and `referrer` or a custom https agent.

---

`isomorphic-fetch` uses `node-fetch` https://www.npmjs.com/package/node-fetch

Looking at the docs here: https://www.npmjs.com/package/node-fetch#api

**Options**

```
{
    // These properties are part of the Fetch Standard
    method: 'GET',
    headers: {},        // request headers. format is the identical to that accepted by the Headers constructor (see below)
    body: null,         // request body. can be null, a string, a Buffer, a Blob, or a Node.js Readable stream
    redirect: 'follow', // set to `manual` to extract redirect headers, `error` to reject redirect
 
    // The following properties are node-fetch extensions
    follow: 20,         // maximum redirect count. 0 to not follow redirect
    timeout: 0,         // req/res timeout in ms, it resets on redirect. 0 to disable (OS limit applies)
    compress: true,     // support gzip/deflate content encoding. false to disable
    size: 0,            // maximum response body size in bytes. 0 to disable
    agent: null         // http(s).Agent instance, allows custom proxy, certificate etc.
}
```

##### Default Headers

If no values are set, the following request headers will be sent automatically:

Header            | Value
----------------- | --------------------------------------------------------
`Accept-Encoding` | `gzip,deflate` _(when `options.compress === true`)_
`Accept`          | `*/*`
`Connection`      | `close` _(when no `options.agent` is present)_
`Content-Length`  | _(automatically calculated, if possible)_
`User-Agent`      | `node-fetch/1.0 (+https://github.com/bitinn/node-fetch)`

---

So we want to be setting `User-Agent` at the very least to a proper browser user agent. Being able to set `agent` allows us to set a proxy-pass ip and port without having to host a proxied version of hltv if we so wish to.

If you're happy with that solution I can put together a PR.

**Comment by gigobyte** [comment]
I've added another optional parameter to the HLTV configuration in v2.8.0 - `loadPage`. It allows you to replace the default fetching library with any function that takes a url and returns a Promise of the response body (`(url: string) => Promise<string>`)
