### ISSUE TITLE
method who won the first round. from the map

### ISSUE THREAD

**Issue by renanrrodrigues** [gigobyte/HLTV#510]
Hi thanks for the API!.

I would like to know if you have any method that I can get on a stats map who won the first round
https://i.ibb.co/4MXGVHv/firsraund.png

edit:

there's this statistic, it's very interesting but it only takes the top teams <50

https://i.ibb.co/X3CNtc6/firsraundtop50.png

@gigobyte

**Comment by gigobyte** [comment]
There is no such method, if anyone wants to contribute to the library they are free to do so.
