### ISSUE TITLE
No events in getMatches

### ISSUE THREAD

**Issue by alexmoruz** [gigobyte/HLTV#514]
Hello!
Seems that there has been a design change on HLTV.org and currently the getMatches method does not return all matches with event object inside.
I think that is caused by the icons highlighted in the image[
<img width="545" alt="Screenshot 2021-09-29 at 13 41 41" src="https://user-images.githubusercontent.com/1496632/135261616-67ac3b04-c94c-4bba-8324-450dcb522f59.png">
](URL)

Could someone please check this out?

Kind regards,
Alex

**Comment by Drachenfalke12** [comment]
fix in #531
