### ISSUE TITLE
Return empty array on every request since last night

### ISSUE THREAD

**Issue by madsj1** [gigobyte/HLTV#52]
Hello, since last night the api returns a empty array on every call, did HLTV change something to break the api?
I checked hltv and it does not seem like i am ip banned.

**Comment by lucaspalencia** [comment]
Same thing here, i had this project (https://github.com/lucaspalencia/cs-go) using the API and all methods returns empty array

**Comment by gigobyte** [comment]
I will check it out and there'll probably be a fix until the end of the day.

**Comment by gigobyte** [comment]
Unfortunately HLTV has CloudFlare DDoS protection enabled. All requests respond with:

> Please turn JavaScript on and reload the page... Checking your browser before accessing

**Comment by gigobyte** [comment]
I switched from using pure fetch to a custom implementation (https://github.com/codemanki/cloudscraper) that can bypass CloudFlare.

**Comment by mavrick** [comment]
Nice! https://www.youtube.com/watch?v=PVF9lZ-i_ss

**Comment by mavrick** [comment]
also, fyi @gigobyte - cloudflare anti-ddos can sometimes run recaptcha, so logging into a google account first then talking to hltv would help bypass the recaptcha check using a cookie jar. relating to https://github.com/gigobyte/HLTV/issues/51 and passing in custom headers or a custom requestjs object now you're using cloudscraper
