### ISSUE TITLE
Split problem with connectToScorebot

### ISSUE THREAD

**Issue by Rtlagot** [gigobyte/HLTV#540]
Hi there,

I know this issue has already happened before, but I tried eveything I could find on the issues and couldn't resolve mine. I've tried with different match id and none worked so far.

I've checked in the lib code, and saw that you look for this in the page source to get the info :

`var url = $('#scoreboardElement')
                .attr('data-scorebot-url')`

Thing is, I couldn't find those tags in the source code of the page. Maybe HTLV uploaded their source code ?

Thanks for taking a look at it,

Fiz

**Comment by Rtlagot** [comment]
Also I know that my IP is not banned because I can use other requests

**Comment by Rtlagot** [comment]
Maybe it was a dumb question from my part, game has to be live for it to work. Is there any way to get the logs of a finished game ?

**Comment by Revilum** [comment]
> Maybe it was a dumb question from my part, game has to be live for it to work. Is there any way to get the logs of a finished game ?

the game has to be live on order for the scorebot to work. If you go to HLTV on live matches there is a live killfeed which is what the scorebot reads.

**Comment by gigobyte** [comment]
It's not possible to get the logs of a finished game.
