### ISSUE TITLE
Getting only 1 page with getResults

### ISSUE THREAD

**Issue by MarianoMolina** [gigobyte/HLTV#544]
Hey! I'm not sure if I'm doing something wrong or if I'm missing something but here is my call:

`HLTV.getResults({startDate: firstDateISO, endDate: endDateISO, rankingFilter: 'Top30', delayBetweenPageRequests: 100})`

With: 
First date:  2020-10-02
End date:  2021-12-26

But I'm only getting the latests results, with: 
Match id: 2353769 Match Date: 2021-12-15T20:12:46.000Z >> Oldest match received
Match id: 2353847 Match Date: 2021-12-26T21:13:22.000Z >> Latest match received

Also, the ranking filter doesn't seem to work. 

What am I doing wrong?

**Comment by MarianoMolina** [comment]
Btw, happy holidays!

**Comment by Drachenfalke12** [comment]
Hey,

I couldn't find a ranking filter at https://www.hltv.org/results, so I believe that this function is just outdated and Hltv removed it or something.

**Comment by gigobyte** [comment]
HLTV removed ranking filter for some reason.

**Comment by MarianoMolina** [comment]
Main problem is still present. getResults is only bringing the newest results.
