### ISSUE TITLE
teams - fetching wrong name

### ISSUE THREAD

**Issue by dovydast** [gigobyte/HLTV#55]
Hi, i don't know, but something got changed in the api, cant get a proper team name, it happens with all the teams. You can see even through postman, something is not right. In name - it shows ENCEmousesports, when it should display hellraisers
[preview](http://prntscr.com/k2e4yz)

**Comment by gigobyte** [comment]
Looks like HLTV have changed their layout again. Thanks for the report, will look into it soon

**Comment by madsj1** [comment]
I think the issue may be with the endpoint getTeam.ts const name = t$('.team-name').text()
In hltv the class on the div with team name is now class="profile-team-name"

**Comment by dovydast** [comment]
it also has probably a same issue with display result score
it displays "result": "16:8 (9:6; 7:2)STATS"
so i had to use angular pipe- the slice , to cut of the text "STATS"
but if the match is bo1, then there is no STATS, and then i get something like this "16:8 (9:" because i just sliced the string

**Comment by gigobyte** [comment]
Fixed in version 2.7.4
