### ISSUE TITLE
getMatchMapStats is consistently blocked by Cloudflare

### ISSUE THREAD

**Issue by greens1901** [gigobyte/HLTV#572]
I haven't been able to call `getMatchMapStats` so far (unlike other endpoints).

```
const { HLTV } = require('hltv')

HLTV.getMatchMapStats({ id: 135510}).then((res)=> {
    console.log(res)
}).catch((error) => {
    console.log(error)
})
```

```
Error: Access denied | www.hltv.org used Cloudflare to restrict access
...
```

Am I using it incorrectly, or is there a regression?

Thanks

**Comment by gigobyte** [comment]
I can't test the endpoint for the same reason. HLTV has different levels of protection for different pages so I imagine they have a very strict policy for map stats. I still haven't figured out a way to trick it.

**Comment by Revilum** [comment]
I managed to trick it by using [puppeteer](https://github.com/puppeteer/puppeteer) although this would take a lot of resources.

**Comment by greens1901** [comment]
@gigobyte I believe it is because of the performance request `https://www.hltv.org/stats/matches/performance/mapstatsid/${id}/-` as I always get `checking your browser...` message when I try to access it manually.

Perhaps it would make sense to split this one into a separate request, but this will probably cause a breaking change in the schema.

**Comment by greens1901** [comment]
@Revilum nice find, could you fork the repo and add your changes?

**Comment by gigobyte** [comment]
Perhaps we can use something like [cloudscraper](https://www.npmjs.com/package/cloudscraper)

**Comment by humansubn** [comment]
Just spent a few hours messing around, was a relief to see the issue mentioned here. I am a bit novice in troubleshooting these kinds of issues, so if anyone has a solution it would be greatly appreciated.

**Comment by MonsieurBibo** [comment]
Could we use [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr) ? It acts as a proxy that uses puppeteer in order to bypass Cloudflare.

**Comment by MonsieurBibo** [comment]
@humansubn there aren't any ready solutions to this problem, but if you really wants to, you can pass all your requests through FlareSolverr as I suggested, that might be the best and fastest solution.

**Comment by humansubn** [comment]
how do you run the getMatchMapStats command through flaresolverr? right now I can load an hltv page, create a session, and run the request.get to get the query string response of the webpage

**Comment by MonsieurBibo** [comment]
@humansubn Well, if you can do all that, you're pretty much done? You just have to run the result through the scrapper, and you have your info?

**Comment by gigobyte** [comment]
@humansubn You can use
```js
const myHLTV = HLTV.createInstance({ loadPage: (url) => your logic here })
```
