### ISSUE TITLE
Add Match Link and/or Event Name to getResults

### ISSUE THREAD

**Issue by dbalders** [gigobyte/HLTV#611]
Hello,

Would it be possible to add in the event name and/or the link to the match in the getResults function? I used to be able to build the url manually using the event name, but that seems to now be removed from the object in moving from v2 to v3. Could that come back possible or even add in the url so it doesn't have to be built?

Thanks,
David

**Comment by Revilum** [comment]
I think that wouldn't be possible without sending a new request for each result. looking at the html of the [results](https://www.hltv.org/results) it looks like the event id is not present there so we can't extract it from that.

**Comment by dbalders** [comment]
The event ID, no, but the event name and the link to the match are both possible using:

`const link = el.find('a').attr('href')
const eventName = el.find('.event-name').text()`

**Comment by gigobyte** [comment]
This won't be supported.
