### ISSUE TITLE
'odds' field from getMatch() only populated with community odds

### ISSUE THREAD

**Issue by boderama** [gigobyte/HLTV#612]
For upcoming matches the match page on HLTV specifies match odds from providers like bet365 etc. These don't seem to get parsed properly despite there being some code in getMatch that looks like it should do it? Only the 'community' odds are successfully parsed.

I could have a go at fixing myself, but I don't really understand how the parser works!

Thanks in advance

**Comment by gigobyte** [comment]
Fixed in 3.4.2
