### ISSUE TITLE
getMatch Returning Split Error

### ISSUE THREAD

**Issue by dbalders** [gigobyte/HLTV#641]
It seems the getEvent portion of getMatch isnt finding any information and is erroring out.

<img width="744" alt="Screen Shot 2023-03-08 at 8 22 13 AM" src="https://user-images.githubusercontent.com/4715098/223770057-341f7e53-b6dc-4d89-8582-b646a538136c.png">

`name` here is blank, and then the id is breaking cause it is sending over an undefined url to getIdAt.

I don't see any obvious change in hltv though. It looks like it should be working based on the selectors?

<img width="843" alt="Screen Shot 2023-03-08 at 8 23 40 AM" src="https://user-images.githubusercontent.com/4715098/223770415-53252e05-f315-4d18-bb9c-0b1de38455c2.png">

**Comment by dbalders** [comment]
When checking the html from the fetchPage utility, this is what the html looks like. Seems like it has been blocked initially and so maybe thats why its not finding anything?

<img width="680" alt="Screen Shot 2023-03-08 at 12 08 54 PM" src="https://user-images.githubusercontent.com/4715098/223837305-076fc8f7-3b18-45ac-9305-aa50cca5a86a.png">

**Comment by gigobyte** [comment]
Yep, looks like you were throttled. I don't really have time to maintain this library so if you want to contribute I would gradly accept a PR.

All you need is to add another check here: https://github.com/gigobyte/HLTV/blob/master/src/utils.ts#L15

**Comment by dbalders** [comment]
I am getting the same thing on multiple computers at different locations as well as someone who got it letting me know about it. Is it possible I'm not throttled but they have added a check in place somehow? Cause I also can't get this screen to pop up in a browser.

**Comment by gigobyte** [comment]
It's possible they have also enabled CloudFlare protection at all times, I know this is the case with one of the `*Stats` methods. I'm also getting that response.

I think the problem is with the default nodejs headers that trigger CF to make the extra check, there were experiments with adding mock headers to make the library look like a regular user but those also caused issues.

**Comment by dbalders** [comment]
Would that mean this is dead?

**Comment by gigobyte** [comment]
I know that there are paid tools that provide CloudFlare bypass so you can replace the `fetchPage` function with a custom one.

**Comment by teslitsky** [comment]
Found a workaround by using a non-default client.
```ts
import { gotScraping } from 'got-scraping';

const hltv = HLTV.createInstance({
  loadPage: (url: string) => gotScraping({ url }).then((res) => res.body)
});
```

**Comment by MichaelYao88** [comment]
never mind I got it to work by asking chatgpt

**Comment by abramyk-mv** [comment]
Why is the issue closed and marked as complete?
Using such a workaround does not make the HLTV library work properly. It is not sufficient. I would rather leave the issue open to keep in mind that parsing itself still requires inner changes.

**Comment by abramyk-mv** [comment]
Thanks, @gigobyte!
After being few days in prod, I discovered that sometimes some requests still get blocked. So, the solution might require more profound research.

**Comment by teslitsky** [comment]
I think this page may help explore
https://blog.apify.com/crawl-without-getting-blocked/

**Comment by gigobyte** [comment]
@abramyk-mv  The goal of the library is to provide a JSON interface to HLTV's website, it's on the user to guarantee that they have access to the website.

Rotating IPs, sessions, headers/fingerprints and using (arguably illegal) tools to bypass CF will not be part of the library and I do not condone using this library for commercial purposes.

**Comment by abramyk-mv** [comment]
>  The network part of the library is completely customisable for that purpose using HTLV.createInstance.

Definitely, I just wanted to make sure that the instance will still leave customisable. Thanks!
