### ISSUE TITLE
getMatchMapStats returns incomplete playerStats

### ISSUE THREAD

**Issue by rorybush** [gigobyte/HLTV#659]
I have noticed that some games only return the playerStats for one half. 

For example id 151172 returns this for team2 stats:

[
  {
    player: { id: 19738, name: 'Djoko' },
    kills: 3,
    hsKills: 3,
    assists: 1,
    flashAssists: 0,
    deaths: 1,
    KAST: 100,
    killDeathsDifference: 2,
    ADR: 166,
    firstKillsDifference: 1,
    rating1: 3
  },
  {
    player: { id: 19739, name: 'Ex3rcice' },
    kills: 5,
    hsKills: 4,
    assists: 1,
    flashAssists: 0,
    deaths: 0,
    KAST: 100,
    killDeathsDifference: 5,
    ADR: 237.5,
    firstKillsDifference: 1,
    rating1: 4.47
  },
  {
    player: { id: 21523, name: 'Razzmo' },
    kills: 0,
    hsKills: 0,
    assists: 0,
    flashAssists: 0,
    deaths: 1,
    KAST: 100,
    killDeathsDifference: -1,
    ADR: 13,
    firstKillsDifference: 0,
    rating1: 0.9
  },
  {
    player: { id: 13497, name: 'Lucky' },
    kills: 1,
    hsKills: 0,
    assists: 0,
    flashAssists: 0,
    deaths: 0,
    KAST: 100,
    killDeathsDifference: 1,
    ADR: 20.5,
    firstKillsDifference: 0,
    rating1: 1.21
  },
  {
    player: { id: 13138, name: 'Maka' },
    kills: 1,
    hsKills: 1,
    assists: 0,
    flashAssists: 0,
    deaths: 0,
    KAST: 100,
    killDeathsDifference: 1,
    ADR: 63,
    firstKillsDifference: 0,
    rating1: 1.41
  }
]

When looking at the HLTV map stats page, this confirms it's only shows the T side stats for team2 for this game:

<img width="667" alt="Screenshot 2023-04-08 at 10 32 34" src="https://user-images.githubusercontent.com/9086213/230714376-28b41354-875e-4f55-8c8c-3b551f9e49c3.png">

However, when looking at the stats for team1, it returns the stats for both ct and t:

[
  {
    player: { id: 11287, name: 'darko' },
    kills: 7,
    hsKills: 5,
    assists: 4,
    flashAssists: 0,
    deaths: 16,
    KAST: 52.9,
    killDeathsDifference: -9,
    ADR: 74,
    firstKillsDifference: 0,
    rating1: 0.76
  },
  {
    player: { id: 20637, name: 'b1elany' },
    kills: 8,
    hsKills: 4,
    assists: 0,
    flashAssists: 0,
    deaths: 16,
    KAST: 52.9,
    killDeathsDifference: -8,
    ADR: 44.7,
    firstKillsDifference: 1,
    rating1: 0.52
  },
  {
    player: { id: 21763, name: 'ultimate' },
    kills: 6,
    hsKills: 3,
    assists: 0,
    flashAssists: 0,
    deaths: 17,
    KAST: 41.2,
    killDeathsDifference: -11,
    ADR: 31.8,
    firstKillsDifference: -2,
    rating1: 0.36
  },
  {
    player: { id: 22011, name: 'kadziu' },
    kills: 5,
    hsKills: 3,
    assists: 3,
    flashAssists: 0,
    deaths: 17,
    KAST: 35.3,
    killDeathsDifference: -12,
    ADR: 44,
    firstKillsDifference: -2,
    rating1: 0.3
  },
  {
    player: { id: 20246, name: 'gRuChA' },
    kills: 5,
    hsKills: 3,
    assists: 1,
    flashAssists: 0,
    deaths: 16,
    KAST: 47.1,
    killDeathsDifference: -11,
    ADR: 46.2,
    firstKillsDifference: -6,
    rating1: 0.29
  }
]

Here is the [matchpage](https://www.hltv.org/matches/2361876/pge-turow-vs-heet-blasttv-paris-major-2023-europe-rmr-open-qualifier-2). There are other matches that have this bug as well.

**Comment by Zelvar** [comment]
Check my PR#625 or my fork, I was already fixing that in december :-)
