### ISSUE TITLE
All endpoints return an empty array

### ISSUE THREAD

**Issue by adamlower** [gigobyte/HLTV#67]
Hey there @gigobyte, this project seems rad! 

I'm using just a simple little express server and trying to make calls to the API inside of a route. I'm only getting back an empty array, no matter how hard I try. I even tried to use [lucaspalencia's CS:GO CLI project](https://github.com/lucaspalencia/cs-go) and it seems to be suffering from the same issue.

**Comment by gigobyte** [comment]
Have you updated to the latest version (`2.8.1`)? All of the regression tests run successfully, also I ran the `getMatches` method manually to confirm and everything was working.

**Comment by lucaspalencia** [comment]
Hey @adamlower, i had updated the `cs-go` to version (0.2.6) using the HLTV version (2.8.1) and everything works
