### ISSUE TITLE
getMatchesStats results contains 'null'

### ISSUE THREAD

**Issue by Ematrion** [gigobyte/HLTV#693]
A minor issue I encounter is that the data collected using the getMatchesStats did contain two 'null' values for the 'results.team2' field. 

I tried multiple times and got the same results. I was able to find the corresponding game pages:
https://www.hltv.org/matches/2297917/epsilon-vs-awtr-dreamhack-open-cluj-napoca-2015-eu-pre-qualifier-2
https://www.hltv.org/matches/2297915/night-raid-vs-kappakappa-dreamhack-open-cluj-napoca-2015-eu-pre-qualifier-2

Results are visible on multiple places, but the stats page is broken for both, link in 
<div class="results-center-stats">< a href=...

Notes:
1) It was odd not to find the game id in the returned json, only the mapStatsID. I had to find myself manually the ids
2) the getMatch({id : }) works fine in both cases (2297917 & 2297915) no error, results are there.
3) for getMatchesStats the missing value of the game between Epsilon and AWTR is inconsistent with getMatch(2297917):
"result": {
            "team1": 7,
            "team2": null
        }
 versus:
 "result": {
                "team1TotalRounds": 7,
                "team2TotalRounds": 16,
 Again, getMatch gets it correctly.

Finally, I just want to say a big thanks you. I never used JS before and was able to easily collect all the data I needed. Great Documentation and Examples.

**Comment by gigobyte** [comment]
I was not able to reproduce this issue unfortunately, next time please post the options with which `getMatchesStats` was called. There is no match ID in the response because each endpoint in this library corresponds to a single page in HLTV, as you figured it out you can combine different endpoints to get the data you want.
