### ISSUE TITLE
Issue installing v3 or later.

### ISSUE THREAD

**Issue by CharlesBrooks** [gigobyte/HLTV#700]
I'm attempting to use 3.4.6 (i have encountered the error in any of major version 3.x.x), and when building my application i receive the following error. 

![image](https://github.com/gigobyte/HLTV/assets/4098778/d2666ff2-b4f6-4ed3-afe0-bdbbbe3ea45f)

I have however cloned the repo, built, and have been able to use the playground. 

Im not sure if this is a node / npm version discrepancy, or some other compatibility problem with my project.

**Comment by gigobyte** [comment]
What version of TS are you on? I think adding `"skipLibCheck": true` in your tsconfig will fix the problem.

**Comment by CharlesBrooks** [comment]
@gigobyte ah that did it, thank you!
