### ISSUE TITLE
/node_modules/cheerio/lib/index"' has no exported member named 'Root'. Did you mean 'root'?  

### ISSUE THREAD

**Issue by ollebergkvist** [gigobyte/HLTV#735]
Getting this error during build process of an express api (typescript).

```
/node_modules/cheerio/lib/index"' has no exported member named 'Root'. Did you mean 'root'?

2 export interface HLTVPage extends cheerio.Root {
```

And 

```
node_modules/hltv/lib/scraper.d.ts:30:50 - error TS2724: '/node_modules/cheerio/lib/index"' has no exported member named 'Root'. Did you mean 'root'?

30 export declare const HLTVScraper: (root: cheerio.Root) => HLTVPage;
```

(https://cheerio.js.org/docs/api#:~:text=)%3A%20Cheerio-,The%20.,a%20%22loaded%22%20Cheerio%20function.&text=Use%20root%20on%20the%20loaded%20instance%20instead.)

**Comment by petz15** [comment]
Hi, check my closed issue #489. Had the same problem but was a simple fix. just update cheerio.
