### ISSUE TITLE
Add 'date' for 'getResults.ts'

### ISSUE THREAD

**Issue by dsmaxville** [gigobyte/HLTV#77]
I dont use the database for grabbing. I get the data from the saved page cache.

Can you help me get the date for 'getResults.ts'? pls

**Comment by gigobyte** [comment]
Currently there is no way to get the date from a match result, but it will be added soon (think next week).

**Comment by dsmaxville** [comment]
ty!

**Comment by gigobyte** [comment]
Added in `v2.9.0`
