### ISSUE TITLE
Error: Cannot find module 'hltv'

### ISSUE THREAD

**Issue by eruanntion** [gigobyte/HLTV#8]
Hi,

When I simply try to load module, it fails (npm installed module properly). The same thing happens if you test it with npm's runkit:

https://npm.runkit.com/hltv

**Comment by gigobyte** [comment]
Something must have went wrong with the publishing process, I republished the package as version 1.2.11, it should be okay now.

**Comment by eruanntion** [comment]
It works now, thnx!
