### ISSUE TITLE
Error: Access denied | www.hltv.org used Cloudflare to restrict access

### ISSUE THREAD

**Issue by andart71** [gigobyte/HLTV#804]
I get error 

`Error: Access denied | www.hltv.org used Cloudflare to restrict access`

how can I fix this?

**Comment by andart71** [comment]
```
node_modules/hltv/lib/utils.js:56
            op = body.call(thisArg, _);
```

**Comment by gigobyte** [comment]
Please stop spamming issues, your IP got banned by Cloudflare. If you didn't send a lot of requests it will be temporary and if you wait a couple of hours/days it will clear.
