### ISSUE TITLE
Teams Icons

### ISSUE THREAD

**Issue by 0ArturkA** [gigobyte/HLTV#9]
This module does not receive command icons?

**Comment by gigobyte** [comment]
I think this feature is out of scope for the current methods in v2.0.0. Soon I'll implement the getTeam method which will provide a wider range of information about the team, such as icons.

**Comment by 0ArturkA** [comment]
Perhaps the team icon can be obtained from this link - (https://static.hltv.org/images/team/logo/4674) by specifying at the end the id of the command.

**Comment by gigobyte** [comment]
Yes, parsing the team icon is very straightforward, I'm more worried about semantics.

I want to keep the methods as clean as possible, and including the team icon seems unnecessary to me. As you suggested getting the team icon is as easy as adding an id to a link, if you need that functionality for your project you can simply make the team icon link yourself.

**Comment by 0ArturkA** [comment]
Yes, I will do so.  Is it possible to get statistics of a particular team?

**Comment by gigobyte** [comment]
Unfortunately, currently - no.
I have marked this issue as a feature request and I'll get to implementing it soon :)

**Comment by gigobyte** [comment]
Latest verson 2.2.0 adds getTeamStats
